//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.06.20 at 06:10:07 PM HST 
//


package com.facebook.api.schema;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for education_info complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="education_info">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="year" type="{http://api.facebook.com/1.0/}year"/>
 *         &lt;element name="concentrations">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="concentration" type="{http://api.facebook.com/1.0/}concentration" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "education_info", propOrder = {
    "name",
    "year",
    "concentrations"
})
public class EducationInfo {

    @XmlElement(required = true)
    protected String name;
    protected int year;
    @XmlElement(required = true)
    protected EducationInfo.Concentrations concentrations;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public synchronized String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public synchronized void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the year property.
     * 
     */
    public synchronized int getYear() {
        return year;
    }

    /**
     * Sets the value of the year property.
     * 
     */
    public synchronized void setYear(int value) {
        this.year = value;
    }

    /**
     * Gets the value of the concentrations property.
     * 
     * @return
     *     possible object is
     *     {@link EducationInfo.Concentrations }
     *     
     */
    public synchronized EducationInfo.Concentrations getConcentrations() {
        return concentrations;
    }

    /**
     * Sets the value of the concentrations property.
     * 
     * @param value
     *     allowed object is
     *     {@link EducationInfo.Concentrations }
     *     
     */
    public synchronized void setConcentrations(EducationInfo.Concentrations value) {
        this.concentrations = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="concentration" type="{http://api.facebook.com/1.0/}concentration" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "concentration"
    })
    public static class Concentrations {

        protected List<String> concentration;
        @XmlAttribute
        protected Boolean list;

        /**
         * Gets the value of the concentration property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the concentration property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getConcentration().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public synchronized List<String> getConcentration() {
            if (concentration == null) {
                concentration = new ArrayList<String>();
            }
            return this.concentration;
        }

        /**
         * Gets the value of the list property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public synchronized Boolean isList() {
            return list;
        }

        /**
         * Sets the value of the list property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public synchronized void setList(Boolean value) {
            this.list = value;
        }

    }

}
