//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.06.20 at 06:10:07 PM HST 
//


package com.facebook.api.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for hs_info complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="hs_info">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="hs1_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hs2_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="grad_year" type="{http://api.facebook.com/1.0/}year"/>
 *         &lt;element name="hs1_id" type="{http://api.facebook.com/1.0/}hsid"/>
 *         &lt;element name="hs2_id" type="{http://api.facebook.com/1.0/}hsid"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hs_info", propOrder = {
    "hs1Name",
    "hs2Name",
    "gradYear",
    "hs1Id",
    "hs2Id"
})
public class HsInfo {

    @XmlElement(name = "hs1_name", required = true)
    protected String hs1Name;
    @XmlElement(name = "hs2_name", required = true)
    protected String hs2Name;
    @XmlElement(name = "grad_year")
    protected int gradYear;
    @XmlElement(name = "hs1_id")
    protected long hs1Id;
    @XmlElement(name = "hs2_id")
    protected long hs2Id;

    /**
     * Gets the value of the hs1Name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public synchronized String getHs1Name() {
        return hs1Name;
    }

    /**
     * Sets the value of the hs1Name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public synchronized void setHs1Name(String value) {
        this.hs1Name = value;
    }

    /**
     * Gets the value of the hs2Name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public synchronized String getHs2Name() {
        return hs2Name;
    }

    /**
     * Sets the value of the hs2Name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public synchronized void setHs2Name(String value) {
        this.hs2Name = value;
    }

    /**
     * Gets the value of the gradYear property.
     * 
     */
    public synchronized int getGradYear() {
        return gradYear;
    }

    /**
     * Sets the value of the gradYear property.
     * 
     */
    public synchronized void setGradYear(int value) {
        this.gradYear = value;
    }

    /**
     * Gets the value of the hs1Id property.
     * 
     */
    public synchronized long getHs1Id() {
        return hs1Id;
    }

    /**
     * Sets the value of the hs1Id property.
     * 
     */
    public synchronized void setHs1Id(long value) {
        this.hs1Id = value;
    }

    /**
     * Gets the value of the hs2Id property.
     * 
     */
    public synchronized long getHs2Id() {
        return hs2Id;
    }

    /**
     * Sets the value of the hs2Id property.
     * 
     */
    public synchronized void setHs2Id(long value) {
        this.hs2Id = value;
    }

}
