//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.10.27 at 03:31:33 PM PDT 
//


package com.facebook.api.schema;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for listing complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="listing">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="listing_id" type="{http://api.facebook.com/1.0/}lid"/>
 *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="poster" type="{http://api.facebook.com/1.0/}uid"/>
 *         &lt;element name="update_time" type="{http://api.facebook.com/1.0/}time"/>
 *         &lt;element name="category" type="{http://api.facebook.com/1.0/}marketplace_category"/>
 *         &lt;element name="subcategory" type="{http://api.facebook.com/1.0/}marketplace_subcategory"/>
 *         &lt;element name="image_urls" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="image_urls_elt" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="condition" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="isbn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="num_beds" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="num_maths" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dogs" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cats" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="smoking" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="square_footage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="street" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="crossstreet" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="postal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pay" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="full" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="intern" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="summer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nonprofit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pay_type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "listing", propOrder = {
    "listingId",
    "url",
    "title",
    "description",
    "price",
    "poster",
    "updateTime",
    "category",
    "subcategory",
    "imageUrls",
    "condition",
    "isbn",
    "numBeds",
    "numMaths",
    "dogs",
    "cats",
    "smoking",
    "squareFootage",
    "street",
    "crossstreet",
    "postal",
    "rent",
    "pay",
    "full",
    "intern",
    "summer",
    "nonprofit",
    "payType"
})
public class Listing {

    @XmlElement(name = "listing_id")
    protected long listingId;
    @XmlElement(required = true)
    protected String url;
    @XmlElement(required = true)
    protected String title;
    @XmlElement(required = true)
    protected String description;
    protected BigDecimal price;
    protected long poster;
    @XmlElement(name = "update_time")
    protected int updateTime;
    @XmlElement(required = true)
    protected String category;
    @XmlElement(required = true)
    protected String subcategory;
    @XmlElement(name = "image_urls")
    protected Listing.ImageUrls imageUrls;
    protected Integer condition;
    protected String isbn;
    @XmlElement(name = "num_beds")
    protected String numBeds;
    @XmlElement(name = "num_maths")
    protected String numMaths;
    protected String dogs;
    protected String cats;
    protected String smoking;
    @XmlElement(name = "square_footage")
    protected String squareFootage;
    protected String street;
    protected String crossstreet;
    protected String postal;
    protected String rent;
    protected String pay;
    protected String full;
    protected String intern;
    protected String summer;
    protected String nonprofit;
    @XmlElement(name = "pay_type")
    protected String payType;

    /**
     * Gets the value of the listingId property.
     * 
     */
    public long getListingId() {
        return listingId;
    }

    /**
     * Sets the value of the listingId property.
     * 
     */
    public void setListingId(long value) {
        this.listingId = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrl(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrice(BigDecimal value) {
        this.price = value;
    }

    /**
     * Gets the value of the poster property.
     * 
     */
    public long getPoster() {
        return poster;
    }

    /**
     * Sets the value of the poster property.
     * 
     */
    public void setPoster(long value) {
        this.poster = value;
    }

    /**
     * Gets the value of the updateTime property.
     * 
     */
    public int getUpdateTime() {
        return updateTime;
    }

    /**
     * Sets the value of the updateTime property.
     * 
     */
    public void setUpdateTime(int value) {
        this.updateTime = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

    /**
     * Gets the value of the subcategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubcategory() {
        return subcategory;
    }

    /**
     * Sets the value of the subcategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubcategory(String value) {
        this.subcategory = value;
    }

    /**
     * Gets the value of the imageUrls property.
     * 
     * @return
     *     possible object is
     *     {@link Listing.ImageUrls }
     *     
     */
    public Listing.ImageUrls getImageUrls() {
        return imageUrls;
    }

    /**
     * Sets the value of the imageUrls property.
     * 
     * @param value
     *     allowed object is
     *     {@link Listing.ImageUrls }
     *     
     */
    public void setImageUrls(Listing.ImageUrls value) {
        this.imageUrls = value;
    }

    /**
     * Gets the value of the condition property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCondition() {
        return condition;
    }

    /**
     * Sets the value of the condition property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCondition(Integer value) {
        this.condition = value;
    }

    /**
     * Gets the value of the isbn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsbn() {
        return isbn;
    }

    /**
     * Sets the value of the isbn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsbn(String value) {
        this.isbn = value;
    }

    /**
     * Gets the value of the numBeds property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumBeds() {
        return numBeds;
    }

    /**
     * Sets the value of the numBeds property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumBeds(String value) {
        this.numBeds = value;
    }

    /**
     * Gets the value of the numMaths property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumMaths() {
        return numMaths;
    }

    /**
     * Sets the value of the numMaths property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumMaths(String value) {
        this.numMaths = value;
    }

    /**
     * Gets the value of the dogs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDogs() {
        return dogs;
    }

    /**
     * Sets the value of the dogs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDogs(String value) {
        this.dogs = value;
    }

    /**
     * Gets the value of the cats property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCats() {
        return cats;
    }

    /**
     * Sets the value of the cats property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCats(String value) {
        this.cats = value;
    }

    /**
     * Gets the value of the smoking property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSmoking() {
        return smoking;
    }

    /**
     * Sets the value of the smoking property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSmoking(String value) {
        this.smoking = value;
    }

    /**
     * Gets the value of the squareFootage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSquareFootage() {
        return squareFootage;
    }

    /**
     * Sets the value of the squareFootage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSquareFootage(String value) {
        this.squareFootage = value;
    }

    /**
     * Gets the value of the street property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreet() {
        return street;
    }

    /**
     * Sets the value of the street property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreet(String value) {
        this.street = value;
    }

    /**
     * Gets the value of the crossstreet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCrossstreet() {
        return crossstreet;
    }

    /**
     * Sets the value of the crossstreet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCrossstreet(String value) {
        this.crossstreet = value;
    }

    /**
     * Gets the value of the postal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostal() {
        return postal;
    }

    /**
     * Sets the value of the postal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostal(String value) {
        this.postal = value;
    }

    /**
     * Gets the value of the rent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRent() {
        return rent;
    }

    /**
     * Sets the value of the rent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRent(String value) {
        this.rent = value;
    }

    /**
     * Gets the value of the pay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPay() {
        return pay;
    }

    /**
     * Sets the value of the pay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPay(String value) {
        this.pay = value;
    }

    /**
     * Gets the value of the full property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFull() {
        return full;
    }

    /**
     * Sets the value of the full property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFull(String value) {
        this.full = value;
    }

    /**
     * Gets the value of the intern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntern() {
        return intern;
    }

    /**
     * Sets the value of the intern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntern(String value) {
        this.intern = value;
    }

    /**
     * Gets the value of the summer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSummer() {
        return summer;
    }

    /**
     * Sets the value of the summer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSummer(String value) {
        this.summer = value;
    }

    /**
     * Gets the value of the nonprofit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNonprofit() {
        return nonprofit;
    }

    /**
     * Sets the value of the nonprofit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNonprofit(String value) {
        this.nonprofit = value;
    }

    /**
     * Gets the value of the payType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayType() {
        return payType;
    }

    /**
     * Sets the value of the payType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayType(String value) {
        this.payType = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="image_urls_elt" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "imageUrlsElt"
    })
    public static class ImageUrls {

        @XmlElement(name = "image_urls_elt")
        protected List<String> imageUrlsElt;
        @XmlAttribute
        protected Boolean list;

        /**
         * Gets the value of the imageUrlsElt property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the imageUrlsElt property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getImageUrlsElt().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getImageUrlsElt() {
            if (imageUrlsElt == null) {
                imageUrlsElt = new ArrayList<String>();
            }
            return this.imageUrlsElt;
        }

        /**
         * Gets the value of the list property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isList() {
            return list;
        }

        /**
         * Sets the value of the list property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setList(Boolean value) {
            this.list = value;
        }

    }

}
