//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.06.20 at 06:10:07 PM HST 
//


package com.facebook.api.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bigtribe.social.facebook.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PhotosCreateAlbumResponse_QNAME = new QName("http://api.facebook.com/1.0/", "photos_createAlbum_response");
    private final static QName _FbmlSetRefHandleResponse_QNAME = new QName("http://api.facebook.com/1.0/", "fbml_setRefHandle_response");
    private final static QName _AuthGetSessionResponse_QNAME = new QName("http://api.facebook.com/1.0/", "auth_getSession_response");
    private final static QName _GroupsGetMembersResponse_QNAME = new QName("http://api.facebook.com/1.0/", "groups_getMembers_response");
    private final static QName _PhotosUploadResponse_QNAME = new QName("http://api.facebook.com/1.0/", "photos_upload_response");
    private final static QName _UsersGetLoggedInUserResponse_QNAME = new QName("http://api.facebook.com/1.0/", "users_getLoggedInUser_response");
    private final static QName _ErrorResponse_QNAME = new QName("http://api.facebook.com/1.0/", "error_response");
    private final static QName _ProfileSetFBMLResponse_QNAME = new QName("http://api.facebook.com/1.0/", "profile_setFBML_response");
    private final static QName _NotificationsSendResponse_QNAME = new QName("http://api.facebook.com/1.0/", "notifications_send_response");
    private final static QName _AuthCreateTokenResponse_QNAME = new QName("http://api.facebook.com/1.0/", "auth_createToken_response");
    private final static QName _ProfileGetFBMLResponse_QNAME = new QName("http://api.facebook.com/1.0/", "profile_getFBML_response");
    private final static QName _PhotosAddTagResponse_QNAME = new QName("http://api.facebook.com/1.0/", "photos_addTag_response");
    private final static QName _FbmlRefreshImgSrcResponse_QNAME = new QName("http://api.facebook.com/1.0/", "fbml_refreshImgSrc_response");
    private final static QName _NotificationsGetResponse_QNAME = new QName("http://api.facebook.com/1.0/", "notifications_get_response");
    private final static QName _FbmlRefreshRefUrlResponse_QNAME = new QName("http://api.facebook.com/1.0/", "fbml_refreshRefUrl_response");
    private final static QName _FeedPublishActionOfUserResponse_QNAME = new QName("http://api.facebook.com/1.0/", "feed_publishActionOfUser_response");
    private final static QName _EventsGetMembersResponse_QNAME = new QName("http://api.facebook.com/1.0/", "events_getMembers_response");
    private final static QName _UsersIsAppAddedResponse_QNAME = new QName("http://api.facebook.com/1.0/", "users_isAppAdded_response");
    private final static QName _NotificationsSendRequestResponse_QNAME = new QName("http://api.facebook.com/1.0/", "notifications_sendRequest_response");
    private final static QName _FeedPublishStoryToUserResponse_QNAME = new QName("http://api.facebook.com/1.0/", "feed_publishStoryToUser_response");
    private final static QName _UserTv_QNAME = new QName("http://api.facebook.com/1.0/", "tv");
    private final static QName _UserWorkHistory_QNAME = new QName("http://api.facebook.com/1.0/", "work_history");
    private final static QName _UserMeetingFor_QNAME = new QName("http://api.facebook.com/1.0/", "meeting_for");
    private final static QName _UserProfileUpdateTime_QNAME = new QName("http://api.facebook.com/1.0/", "profile_update_time");
    private final static QName _UserHometownLocation_QNAME = new QName("http://api.facebook.com/1.0/", "hometown_location");
    private final static QName _UserReligion_QNAME = new QName("http://api.facebook.com/1.0/", "religion");
    private final static QName _UserBirthday_QNAME = new QName("http://api.facebook.com/1.0/", "birthday");
    private final static QName _UserHsInfo_QNAME = new QName("http://api.facebook.com/1.0/", "hs_info");
    private final static QName _UserMusic_QNAME = new QName("http://api.facebook.com/1.0/", "music");
    private final static QName _UserCurrentLocation_QNAME = new QName("http://api.facebook.com/1.0/", "current_location");
    private final static QName _UserPicBig_QNAME = new QName("http://api.facebook.com/1.0/", "pic_big");
    private final static QName _UserInterests_QNAME = new QName("http://api.facebook.com/1.0/", "interests");
    private final static QName _UserPolitical_QNAME = new QName("http://api.facebook.com/1.0/", "political");
    private final static QName _UserMovies_QNAME = new QName("http://api.facebook.com/1.0/", "movies");
    private final static QName _UserEducationHistory_QNAME = new QName("http://api.facebook.com/1.0/", "education_history");
    private final static QName _UserSignificantOtherId_QNAME = new QName("http://api.facebook.com/1.0/", "significant_other_id");
    private final static QName _UserWallCount_QNAME = new QName("http://api.facebook.com/1.0/", "wall_count");
    private final static QName _UserPicSmall_QNAME = new QName("http://api.facebook.com/1.0/", "pic_small");
    private final static QName _UserTimezone_QNAME = new QName("http://api.facebook.com/1.0/", "timezone");
    private final static QName _UserSex_QNAME = new QName("http://api.facebook.com/1.0/", "sex");
    private final static QName _UserAboutMe_QNAME = new QName("http://api.facebook.com/1.0/", "about_me");
    private final static QName _UserStatus_QNAME = new QName("http://api.facebook.com/1.0/", "status");
    private final static QName _UserActivities_QNAME = new QName("http://api.facebook.com/1.0/", "activities");
    private final static QName _UserRelationshipStatus_QNAME = new QName("http://api.facebook.com/1.0/", "relationship_status");
    private final static QName _UserBooks_QNAME = new QName("http://api.facebook.com/1.0/", "books");
    private final static QName _UserPic_QNAME = new QName("http://api.facebook.com/1.0/", "pic");
    private final static QName _UserPicSquare_QNAME = new QName("http://api.facebook.com/1.0/", "pic_square");
    private final static QName _UserMeetingSex_QNAME = new QName("http://api.facebook.com/1.0/", "meeting_sex");
    private final static QName _UserNotesCount_QNAME = new QName("http://api.facebook.com/1.0/", "notes_count");
    private final static QName _UserQuotes_QNAME = new QName("http://api.facebook.com/1.0/", "quotes");
    private final static QName _FriendInfoAreFriends_QNAME = new QName("http://api.facebook.com/1.0/", "are_friends");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bigtribe.social.facebook.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link FriendsGetAppUsersResponse }
     * 
     */
    public FriendsGetAppUsersResponse createFriendsGetAppUsersResponse() {
        return new FriendsGetAppUsersResponse();
    }

    /**
     * Create an instance of {@link Affiliation }
     * 
     */
    public Affiliation createAffiliation() {
        return new Affiliation();
    }

    /**
     * Create an instance of {@link GroupMember.Positions }
     * 
     */
    public GroupMember.Positions createGroupMemberPositions() {
        return new GroupMember.Positions();
    }

    /**
     * Create an instance of {@link EducationInfo }
     * 
     */
    public EducationInfo createEducationInfo() {
        return new EducationInfo();
    }

    /**
     * Create an instance of {@link HsInfo }
     * 
     */
    public HsInfo createHsInfo() {
        return new HsInfo();
    }

    /**
     * Create an instance of {@link FriendsGetResponse }
     * 
     */
    public FriendsGetResponse createFriendsGetResponse() {
        return new FriendsGetResponse();
    }

    /**
     * Create an instance of {@link EventMembers.NotReplied }
     * 
     */
    public EventMembers.NotReplied createEventMembersNotReplied() {
        return new EventMembers.NotReplied();
    }

    /**
     * Create an instance of {@link Notifications.GroupInvites }
     * 
     */
    public Notifications.GroupInvites createNotificationsGroupInvites() {
        return new Notifications.GroupInvites();
    }

    /**
     * Create an instance of {@link FacebookApiException }
     * 
     */
    public FacebookApiException createFacebookApiException() {
        return new FacebookApiException();
    }

    /**
     * Create an instance of {@link PhotoTag }
     * 
     */
    public PhotoTag createPhotoTag() {
        return new PhotoTag();
    }

    /**
     * Create an instance of {@link FriendInfo }
     * 
     */
    public FriendInfo createFriendInfo() {
        return new FriendInfo();
    }

    /**
     * Create an instance of {@link PhotosGetTagsResponse }
     * 
     */
    public PhotosGetTagsResponse createPhotosGetTagsResponse() {
        return new PhotosGetTagsResponse();
    }

    /**
     * Create an instance of {@link Notifications }
     * 
     */
    public Notifications createNotifications() {
        return new Notifications();
    }

    /**
     * Create an instance of {@link Album }
     * 
     */
    public Album createAlbum() {
        return new Album();
    }

    /**
     * Create an instance of {@link EventMembers.Declined }
     * 
     */
    public EventMembers.Declined createEventMembersDeclined() {
        return new EventMembers.Declined();
    }

    /**
     * Create an instance of {@link GroupMembers.Officers }
     * 
     */
    public GroupMembers.Officers createGroupMembersOfficers() {
        return new GroupMembers.Officers();
    }

    /**
     * Create an instance of {@link Photo }
     * 
     */
    public Photo createPhoto() {
        return new Photo();
    }

    /**
     * Create an instance of {@link UsersGetInfoResponse }
     * 
     */
    public UsersGetInfoResponse createUsersGetInfoResponse() {
        return new UsersGetInfoResponse();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link User.EducationHistory }
     * 
     */
    public User.EducationHistory createUserEducationHistory() {
        return new User.EducationHistory();
    }

    /**
     * Create an instance of {@link EventMembers.Attending }
     * 
     */
    public EventMembers.Attending createEventMembersAttending() {
        return new EventMembers.Attending();
    }

    /**
     * Create an instance of {@link PhotosGetResponse }
     * 
     */
    public PhotosGetResponse createPhotosGetResponse() {
        return new PhotosGetResponse();
    }

    /**
     * Create an instance of {@link EventMembers.Unsure }
     * 
     */
    public EventMembers.Unsure createEventMembersUnsure() {
        return new EventMembers.Unsure();
    }

    /**
     * Create an instance of {@link UserStatus }
     * 
     */
    public UserStatus createUserStatus() {
        return new UserStatus();
    }

    /**
     * Create an instance of {@link EducationInfo.Concentrations }
     * 
     */
    public EducationInfo.Concentrations createEducationInfoConcentrations() {
        return new EducationInfo.Concentrations();
    }

    /**
     * Create an instance of {@link Notifications.EventInvites }
     * 
     */
    public Notifications.EventInvites createNotificationsEventInvites() {
        return new Notifications.EventInvites();
    }

    /**
     * Create an instance of {@link EventMember }
     * 
     */
    public EventMember createEventMember() {
        return new EventMember();
    }

    /**
     * Create an instance of {@link User.Affiliations }
     * 
     */
    public User.Affiliations createUserAffiliations() {
        return new User.Affiliations();
    }

    /**
     * Create an instance of {@link GroupsGetResponse }
     * 
     */
    public GroupsGetResponse createGroupsGetResponse() {
        return new GroupsGetResponse();
    }

    /**
     * Create an instance of {@link NotificationCount }
     * 
     */
    public NotificationCount createNotificationCount() {
        return new NotificationCount();
    }

    /**
     * Create an instance of {@link User.MeetingSex }
     * 
     */
    public User.MeetingSex createUserMeetingSex() {
        return new User.MeetingSex();
    }

    /**
     * Create an instance of {@link IdMap }
     * 
     */
    public IdMap createIdMap() {
        return new IdMap();
    }

    /**
     * Create an instance of {@link GroupMembers.Members }
     * 
     */
    public GroupMembers.Members createGroupMembersMembers() {
        return new GroupMembers.Members();
    }

    /**
     * Create an instance of {@link SessionInfo }
     * 
     */
    public SessionInfo createSessionInfo() {
        return new SessionInfo();
    }

    /**
     * Create an instance of {@link User.WorkHistory }
     * 
     */
    public User.WorkHistory createUserWorkHistory() {
        return new User.WorkHistory();
    }

    /**
     * Create an instance of {@link GroupMembers.NotReplied }
     * 
     */
    public GroupMembers.NotReplied createGroupMembersNotReplied() {
        return new GroupMembers.NotReplied();
    }

    /**
     * Create an instance of {@link PhotosGetAlbumsResponse }
     * 
     */
    public PhotosGetAlbumsResponse createPhotosGetAlbumsResponse() {
        return new PhotosGetAlbumsResponse();
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link Arg }
     * 
     */
    public Arg createArg() {
        return new Arg();
    }

    /**
     * Create an instance of {@link Notifications.FriendRequests }
     * 
     */
    public Notifications.FriendRequests createNotificationsFriendRequests() {
        return new Notifications.FriendRequests();
    }

    /**
     * Create an instance of {@link Event }
     * 
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link GroupMember }
     * 
     */
    public GroupMember createGroupMember() {
        return new GroupMember();
    }

    /**
     * Create an instance of {@link User.MeetingFor }
     * 
     */
    public User.MeetingFor createUserMeetingFor() {
        return new User.MeetingFor();
    }

    /**
     * Create an instance of {@link UpdateDecodeIDsResponse }
     * 
     */
    public UpdateDecodeIDsResponse createUpdateDecodeIDsResponse() {
        return new UpdateDecodeIDsResponse();
    }

    /**
     * Create an instance of {@link FriendsAreFriendsResponse }
     * 
     */
    public FriendsAreFriendsResponse createFriendsAreFriendsResponse() {
        return new FriendsAreFriendsResponse();
    }

    /**
     * Create an instance of {@link WorkInfo }
     * 
     */
    public WorkInfo createWorkInfo() {
        return new WorkInfo();
    }

    /**
     * Create an instance of {@link GroupMembers }
     * 
     */
    public GroupMembers createGroupMembers() {
        return new GroupMembers();
    }

    /**
     * Create an instance of {@link EventsGetResponse }
     * 
     */
    public EventsGetResponse createEventsGetResponse() {
        return new EventsGetResponse();
    }

    /**
     * Create an instance of {@link FacebookApiException.RequestArgs }
     * 
     */
    public FacebookApiException.RequestArgs createFacebookApiExceptionRequestArgs() {
        return new FacebookApiException.RequestArgs();
    }

    /**
     * Create an instance of {@link GroupMembers.Admins }
     * 
     */
    public GroupMembers.Admins createGroupMembersAdmins() {
        return new GroupMembers.Admins();
    }

    /**
     * Create an instance of {@link EventMembers }
     * 
     */
    public EventMembers createEventMembers() {
        return new EventMembers();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Album }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "photos_createAlbum_response")
    public JAXBElement<Album> createPhotosCreateAlbumResponse(Album value) {
        return new JAXBElement<Album>(_PhotosCreateAlbumResponse_QNAME, Album.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "fbml_setRefHandle_response")
    public JAXBElement<Boolean> createFbmlSetRefHandleResponse(Boolean value) {
        return new JAXBElement<Boolean>(_FbmlSetRefHandleResponse_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SessionInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "auth_getSession_response")
    public JAXBElement<SessionInfo> createAuthGetSessionResponse(SessionInfo value) {
        return new JAXBElement<SessionInfo>(_AuthGetSessionResponse_QNAME, SessionInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GroupMembers }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "groups_getMembers_response")
    public JAXBElement<GroupMembers> createGroupsGetMembersResponse(GroupMembers value) {
        return new JAXBElement<GroupMembers>(_GroupsGetMembersResponse_QNAME, GroupMembers.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Photo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "photos_upload_response")
    public JAXBElement<Photo> createPhotosUploadResponse(Photo value) {
        return new JAXBElement<Photo>(_PhotosUploadResponse_QNAME, Photo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "users_getLoggedInUser_response")
    public JAXBElement<Integer> createUsersGetLoggedInUserResponse(Integer value) {
        return new JAXBElement<Integer>(_UsersGetLoggedInUserResponse_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FacebookApiException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "error_response")
    public JAXBElement<FacebookApiException> createErrorResponse(FacebookApiException value) {
        return new JAXBElement<FacebookApiException>(_ErrorResponse_QNAME, FacebookApiException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "profile_setFBML_response")
    public JAXBElement<Boolean> createProfileSetFBMLResponse(Boolean value) {
        return new JAXBElement<Boolean>(_ProfileSetFBMLResponse_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "notifications_send_response")
    public JAXBElement<String> createNotificationsSendResponse(String value) {
        return new JAXBElement<String>(_NotificationsSendResponse_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "auth_createToken_response")
    public JAXBElement<String> createAuthCreateTokenResponse(String value) {
        return new JAXBElement<String>(_AuthCreateTokenResponse_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "profile_getFBML_response")
    public JAXBElement<String> createProfileGetFBMLResponse(String value) {
        return new JAXBElement<String>(_ProfileGetFBMLResponse_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "photos_addTag_response")
    public JAXBElement<Boolean> createPhotosAddTagResponse(Boolean value) {
        return new JAXBElement<Boolean>(_PhotosAddTagResponse_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "fbml_refreshImgSrc_response")
    public JAXBElement<Boolean> createFbmlRefreshImgSrcResponse(Boolean value) {
        return new JAXBElement<Boolean>(_FbmlRefreshImgSrcResponse_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Notifications }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "notifications_get_response")
    public JAXBElement<Notifications> createNotificationsGetResponse(Notifications value) {
        return new JAXBElement<Notifications>(_NotificationsGetResponse_QNAME, Notifications.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "fbml_refreshRefUrl_response")
    public JAXBElement<Boolean> createFbmlRefreshRefUrlResponse(Boolean value) {
        return new JAXBElement<Boolean>(_FbmlRefreshRefUrlResponse_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "feed_publishActionOfUser_response")
    public JAXBElement<Boolean> createFeedPublishActionOfUserResponse(Boolean value) {
        return new JAXBElement<Boolean>(_FeedPublishActionOfUserResponse_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EventMembers }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "events_getMembers_response")
    public JAXBElement<EventMembers> createEventsGetMembersResponse(EventMembers value) {
        return new JAXBElement<EventMembers>(_EventsGetMembersResponse_QNAME, EventMembers.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "users_isAppAdded_response")
    public JAXBElement<Boolean> createUsersIsAppAddedResponse(Boolean value) {
        return new JAXBElement<Boolean>(_UsersIsAppAddedResponse_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "notifications_sendRequest_response")
    public JAXBElement<String> createNotificationsSendRequestResponse(String value) {
        return new JAXBElement<String>(_NotificationsSendRequestResponse_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "feed_publishStoryToUser_response")
    public JAXBElement<Boolean> createFeedPublishStoryToUserResponse(Boolean value) {
        return new JAXBElement<Boolean>(_FeedPublishStoryToUserResponse_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "tv", scope = User.class)
    public JAXBElement<String> createUserTv(String value) {
        return new JAXBElement<String>(_UserTv_QNAME, String.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link User.WorkHistory }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "work_history", scope = User.class)
    public JAXBElement<User.WorkHistory> createUserWorkHistory(User.WorkHistory value) {
        return new JAXBElement<User.WorkHistory>(_UserWorkHistory_QNAME, User.WorkHistory.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link User.MeetingFor }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "meeting_for", scope = User.class)
    public JAXBElement<User.MeetingFor> createUserMeetingFor(User.MeetingFor value) {
        return new JAXBElement<User.MeetingFor>(_UserMeetingFor_QNAME, User.MeetingFor.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "profile_update_time", scope = User.class)
    public JAXBElement<Integer> createUserProfileUpdateTime(Integer value) {
        return new JAXBElement<Integer>(_UserProfileUpdateTime_QNAME, Integer.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Location }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "hometown_location", scope = User.class)
    public JAXBElement<Location> createUserHometownLocation(Location value) {
        return new JAXBElement<Location>(_UserHometownLocation_QNAME, Location.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "religion", scope = User.class)
    public JAXBElement<String> createUserReligion(String value) {
        return new JAXBElement<String>(_UserReligion_QNAME, String.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "birthday", scope = User.class)
    public JAXBElement<String> createUserBirthday(String value) {
        return new JAXBElement<String>(_UserBirthday_QNAME, String.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HsInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "hs_info", scope = User.class)
    public JAXBElement<HsInfo> createUserHsInfo(HsInfo value) {
        return new JAXBElement<HsInfo>(_UserHsInfo_QNAME, HsInfo.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "music", scope = User.class)
    public JAXBElement<String> createUserMusic(String value) {
        return new JAXBElement<String>(_UserMusic_QNAME, String.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Location }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "current_location", scope = User.class)
    public JAXBElement<Location> createUserCurrentLocation(Location value) {
        return new JAXBElement<Location>(_UserCurrentLocation_QNAME, Location.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "pic_big", scope = User.class)
    public JAXBElement<String> createUserPicBig(String value) {
        return new JAXBElement<String>(_UserPicBig_QNAME, String.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "interests", scope = User.class)
    public JAXBElement<String> createUserInterests(String value) {
        return new JAXBElement<String>(_UserInterests_QNAME, String.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "political", scope = User.class)
    public JAXBElement<String> createUserPolitical(String value) {
        return new JAXBElement<String>(_UserPolitical_QNAME, String.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "movies", scope = User.class)
    public JAXBElement<String> createUserMovies(String value) {
        return new JAXBElement<String>(_UserMovies_QNAME, String.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link User.EducationHistory }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "education_history", scope = User.class)
    public JAXBElement<User.EducationHistory> createUserEducationHistory(User.EducationHistory value) {
        return new JAXBElement<User.EducationHistory>(_UserEducationHistory_QNAME, User.EducationHistory.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "significant_other_id", scope = User.class)
    public JAXBElement<Integer> createUserSignificantOtherId(Integer value) {
        return new JAXBElement<Integer>(_UserSignificantOtherId_QNAME, Integer.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "wall_count", scope = User.class)
    public JAXBElement<Integer> createUserWallCount(Integer value) {
        return new JAXBElement<Integer>(_UserWallCount_QNAME, Integer.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "pic_small", scope = User.class)
    public JAXBElement<String> createUserPicSmall(String value) {
        return new JAXBElement<String>(_UserPicSmall_QNAME, String.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "timezone", scope = User.class)
    public JAXBElement<Integer> createUserTimezone(Integer value) {
        return new JAXBElement<Integer>(_UserTimezone_QNAME, Integer.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "sex", scope = User.class)
    public JAXBElement<String> createUserSex(String value) {
        return new JAXBElement<String>(_UserSex_QNAME, String.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "about_me", scope = User.class)
    public JAXBElement<String> createUserAboutMe(String value) {
        return new JAXBElement<String>(_UserAboutMe_QNAME, String.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "status", scope = User.class)
    public JAXBElement<UserStatus> createUserStatus(UserStatus value) {
        return new JAXBElement<UserStatus>(_UserStatus_QNAME, UserStatus.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "activities", scope = User.class)
    public JAXBElement<String> createUserActivities(String value) {
        return new JAXBElement<String>(_UserActivities_QNAME, String.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "relationship_status", scope = User.class)
    public JAXBElement<String> createUserRelationshipStatus(String value) {
        return new JAXBElement<String>(_UserRelationshipStatus_QNAME, String.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "books", scope = User.class)
    public JAXBElement<String> createUserBooks(String value) {
        return new JAXBElement<String>(_UserBooks_QNAME, String.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "pic", scope = User.class)
    public JAXBElement<String> createUserPic(String value) {
        return new JAXBElement<String>(_UserPic_QNAME, String.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "pic_square", scope = User.class)
    public JAXBElement<String> createUserPicSquare(String value) {
        return new JAXBElement<String>(_UserPicSquare_QNAME, String.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link User.MeetingSex }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "meeting_sex", scope = User.class)
    public JAXBElement<User.MeetingSex> createUserMeetingSex(User.MeetingSex value) {
        return new JAXBElement<User.MeetingSex>(_UserMeetingSex_QNAME, User.MeetingSex.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "notes_count", scope = User.class)
    public JAXBElement<Integer> createUserNotesCount(Integer value) {
        return new JAXBElement<Integer>(_UserNotesCount_QNAME, Integer.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "quotes", scope = User.class)
    public JAXBElement<String> createUserQuotes(String value) {
        return new JAXBElement<String>(_UserQuotes_QNAME, String.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.facebook.com/1.0/", name = "are_friends", scope = FriendInfo.class)
    public JAXBElement<Boolean> createFriendInfoAreFriends(Boolean value) {
        return new JAXBElement<Boolean>(_FriendInfoAreFriends_QNAME, Boolean.class, FriendInfo.class, value);
    }

}
