//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.07.20 at 05:29:33 PM PDT 
//


package com.facebook.api.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for template_bundle complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="template_bundle">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="one_line_story_templates">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="one_line_story_template" type="{http://api.facebook.com/1.0/}one_line_story_template" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="short_story_templates">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="short_story_template" type="{http://api.facebook.com/1.0/}short_story_template" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="full_story_template" type="{http://api.facebook.com/1.0/}full_story_template"/>
 *         &lt;element name="time_created" type="{http://api.facebook.com/1.0/}time"/>
 *         &lt;element name="template_bundle_id" type="{http://api.facebook.com/1.0/}tbid"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "template_bundle", propOrder = {
    "oneLineStoryTemplates",
    "shortStoryTemplates",
    "fullStoryTemplate",
    "timeCreated",
    "templateBundleId"
})
public class TemplateBundle {

    @XmlElement(name = "one_line_story_templates", required = true)
    protected TemplateBundle.OneLineStoryTemplates oneLineStoryTemplates;
    @XmlElement(name = "short_story_templates", required = true)
    protected TemplateBundle.ShortStoryTemplates shortStoryTemplates;
    @XmlElement(name = "full_story_template", required = true)
    protected FullStoryTemplate fullStoryTemplate;
    @XmlElement(name = "time_created")
    protected int timeCreated;
    @XmlElement(name = "template_bundle_id")
    protected long templateBundleId;

    /**
     * Gets the value of the oneLineStoryTemplates property.
     * 
     * @return
     *     possible object is
     *     {@link TemplateBundle.OneLineStoryTemplates }
     *     
     */
    public TemplateBundle.OneLineStoryTemplates getOneLineStoryTemplates() {
        return oneLineStoryTemplates;
    }

    /**
     * Sets the value of the oneLineStoryTemplates property.
     * 
     * @param value
     *     allowed object is
     *     {@link TemplateBundle.OneLineStoryTemplates }
     *     
     */
    public void setOneLineStoryTemplates(TemplateBundle.OneLineStoryTemplates value) {
        this.oneLineStoryTemplates = value;
    }

    /**
     * Gets the value of the shortStoryTemplates property.
     * 
     * @return
     *     possible object is
     *     {@link TemplateBundle.ShortStoryTemplates }
     *     
     */
    public TemplateBundle.ShortStoryTemplates getShortStoryTemplates() {
        return shortStoryTemplates;
    }

    /**
     * Sets the value of the shortStoryTemplates property.
     * 
     * @param value
     *     allowed object is
     *     {@link TemplateBundle.ShortStoryTemplates }
     *     
     */
    public void setShortStoryTemplates(TemplateBundle.ShortStoryTemplates value) {
        this.shortStoryTemplates = value;
    }

    /**
     * Gets the value of the fullStoryTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link FullStoryTemplate }
     *     
     */
    public FullStoryTemplate getFullStoryTemplate() {
        return fullStoryTemplate;
    }

    /**
     * Sets the value of the fullStoryTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link FullStoryTemplate }
     *     
     */
    public void setFullStoryTemplate(FullStoryTemplate value) {
        this.fullStoryTemplate = value;
    }

    /**
     * Gets the value of the timeCreated property.
     * 
     */
    public int getTimeCreated() {
        return timeCreated;
    }

    /**
     * Sets the value of the timeCreated property.
     * 
     */
    public void setTimeCreated(int value) {
        this.timeCreated = value;
    }

    /**
     * Gets the value of the templateBundleId property.
     * 
     */
    public long getTemplateBundleId() {
        return templateBundleId;
    }

    /**
     * Sets the value of the templateBundleId property.
     * 
     */
    public void setTemplateBundleId(long value) {
        this.templateBundleId = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="one_line_story_template" type="{http://api.facebook.com/1.0/}one_line_story_template" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "oneLineStoryTemplate"
    })
    public static class OneLineStoryTemplates {

        @XmlElement(name = "one_line_story_template")
        protected List<String> oneLineStoryTemplate;
        @XmlAttribute
        protected Boolean list;

        /**
         * Gets the value of the oneLineStoryTemplate property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the oneLineStoryTemplate property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOneLineStoryTemplate().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getOneLineStoryTemplate() {
            if (oneLineStoryTemplate == null) {
                oneLineStoryTemplate = new ArrayList<String>();
            }
            return this.oneLineStoryTemplate;
        }

        /**
         * Gets the value of the list property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isList() {
            return list;
        }

        /**
         * Sets the value of the list property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setList(Boolean value) {
            this.list = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="short_story_template" type="{http://api.facebook.com/1.0/}short_story_template" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "shortStoryTemplate"
    })
    public static class ShortStoryTemplates {

        @XmlElement(name = "short_story_template")
        protected List<ShortStoryTemplate> shortStoryTemplate;
        @XmlAttribute
        protected Boolean list;

        /**
         * Gets the value of the shortStoryTemplate property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the shortStoryTemplate property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getShortStoryTemplate().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ShortStoryTemplate }
         * 
         * 
         */
        public List<ShortStoryTemplate> getShortStoryTemplate() {
            if (shortStoryTemplate == null) {
                shortStoryTemplate = new ArrayList<ShortStoryTemplate>();
            }
            return this.shortStoryTemplate;
        }

        /**
         * Gets the value of the list property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isList() {
            return list;
        }

        /**
         * Sets the value of the list property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setList(Boolean value) {
            this.list = value;
        }

    }

}
