//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.07 at 02:14:09 AM PST 
//


package com.facebook.api.schema;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for user complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="user">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="about_me" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="activities" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="affiliations" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="affiliation" type="{http://api.facebook.com/1.0/}affiliation" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="birthday" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="books" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="current_location" type="{http://api.facebook.com/1.0/}location" minOccurs="0"/>
 *         &lt;element name="education_history" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="education_info" type="{http://api.facebook.com/1.0/}education_info" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="first_name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="hometown_location" type="{http://api.facebook.com/1.0/}location" minOccurs="0"/>
 *         &lt;element name="hs_info" type="{http://api.facebook.com/1.0/}hs_info" minOccurs="0"/>
 *         &lt;element name="interests" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="is_app_user" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="last_name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="meeting_for" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="seeking" type="{http://api.facebook.com/1.0/}seeking" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="meeting_sex" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="sex" type="{http://api.facebook.com/1.0/}sex" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="movies" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="music" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="notes_count" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="pic" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pic_big" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pic_small" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="political" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="profile_update_time" type="{http://api.facebook.com/1.0/}time" minOccurs="0"/>
 *         &lt;element name="quotes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="relationship_status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="religion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sex" type="{http://api.facebook.com/1.0/}sex" minOccurs="0"/>
 *         &lt;element name="significant_other_id" type="{http://api.facebook.com/1.0/}uid" minOccurs="0"/>
 *         &lt;element name="status" type="{http://api.facebook.com/1.0/}user_status" minOccurs="0"/>
 *         &lt;element name="timezone" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="tv" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="uid" type="{http://api.facebook.com/1.0/}uid" minOccurs="0"/>
 *         &lt;element name="wall_count" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="work_history" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="work_info" type="{http://api.facebook.com/1.0/}work_info" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="pic_square" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="has_added_app" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "user", propOrder = {

})
public class User {

    @XmlElementRef(name = "about_me", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> aboutMe;
    @XmlElementRef(name = "activities", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> activities;
    protected User.Affiliations affiliations;
    @XmlElementRef(name = "birthday", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> birthday;
    @XmlElementRef(name = "books", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> books;
    @XmlElementRef(name = "current_location", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<Location> currentLocation;
    @XmlElementRef(name = "education_history", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<User.EducationHistory> educationHistory;
    @XmlElement(name = "first_name")
    protected String firstName;
    @XmlElementRef(name = "hometown_location", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<Location> hometownLocation;
    @XmlElementRef(name = "hs_info", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<HsInfo> hsInfo;
    @XmlElementRef(name = "interests", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> interests;
    @XmlElement(name = "is_app_user")
    protected Boolean isAppUser;
    @XmlElement(name = "last_name")
    protected String lastName;
    @XmlElementRef(name = "meeting_for", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<User.MeetingFor> meetingFor;
    @XmlElementRef(name = "meeting_sex", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<User.MeetingSex> meetingSex;
    @XmlElementRef(name = "movies", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> movies;
    @XmlElementRef(name = "music", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> music;
    protected String name;
    @XmlElementRef(name = "notes_count", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<Integer> notesCount;
    @XmlElementRef(name = "pic", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> pic;
    @XmlElementRef(name = "pic_big", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> picBig;
    @XmlElementRef(name = "pic_small", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> picSmall;
    @XmlElementRef(name = "political", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> political;
    @XmlElementRef(name = "profile_update_time", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<Integer> profileUpdateTime;
    @XmlElementRef(name = "quotes", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> quotes;
    @XmlElementRef(name = "relationship_status", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> relationshipStatus;
    @XmlElementRef(name = "religion", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> religion;
    @XmlElementRef(name = "sex", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> sex;
    @XmlElementRef(name = "significant_other_id", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<Long> significantOtherId;
    @XmlElementRef(name = "status", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<UserStatus> status;
    @XmlElementRef(name = "timezone", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<BigDecimal> timezone;
    @XmlElementRef(name = "tv", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> tv;
    protected Long uid;
    @XmlElementRef(name = "wall_count", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<Integer> wallCount;
    @XmlElementRef(name = "work_history", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<User.WorkHistory> workHistory;
    @XmlElementRef(name = "pic_square", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> picSquare;
    @XmlElementRef(name = "has_added_app", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<Boolean> hasAddedApp;

    /**
     * Gets the value of the aboutMe property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public synchronized String getAboutMe() {
        return aboutMe.getValue();
    }

    /**
     * Sets the value of the aboutMe property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAboutMe(JAXBElement<String> value) {
        this.aboutMe = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the activities property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public synchronized String getActivities() {
        return activities.getValue();
    }

    /**
     * Sets the value of the activities property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setActivities(JAXBElement<String> value) {
        this.activities = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the affiliations property.
     * 
     * @return
     *     possible object is
     *     {@link User.Affiliations }
     *     
     */
    public User.Affiliations getAffiliations() {
        return affiliations;
    }

    /**
     * Sets the value of the affiliations property.
     * 
     * @param value
     *     allowed object is
     *     {@link User.Affiliations }
     *     
     */
    public void setAffiliations(User.Affiliations value) {
        this.affiliations = value;
    }

    /**
     * Gets the value of the birthday property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public synchronized String getBirthday() {
        return birthday.getValue();
    }

    /**
     * Sets the value of the birthday property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setBirthday(JAXBElement<String> value) {
        this.birthday = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the books property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public synchronized String getBooks() {
        return books.getValue();
    }

    /**
     * Sets the value of the books property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setBooks(JAXBElement<String> value) {
        this.books = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the currentLocation property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Location }{@code >}
     *     
     */
    public JAXBElement<Location> getCurrentLocation() {
        return currentLocation;
    }

    /**
     * Sets the value of the currentLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Location }{@code >}
     *     
     */
    public void setCurrentLocation(JAXBElement<Location> value) {
        this.currentLocation = ((JAXBElement<Location> ) value);
    }

    /**
     * Gets the value of the educationHistory property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link User.EducationHistory }{@code >}
     *     
     */
    public JAXBElement<User.EducationHistory> getEducationHistory() {
        return educationHistory;
    }

    /**
     * Sets the value of the educationHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link User.EducationHistory }{@code >}
     *     
     */
    public void setEducationHistory(JAXBElement<User.EducationHistory> value) {
        this.educationHistory = ((JAXBElement<User.EducationHistory> ) value);
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the hometownLocation property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Location }{@code >}
     *     
     */
    public JAXBElement<Location> getHometownLocation() {
        return hometownLocation;
    }

    /**
     * Sets the value of the hometownLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Location }{@code >}
     *     
     */
    public void setHometownLocation(JAXBElement<Location> value) {
        this.hometownLocation = ((JAXBElement<Location> ) value);
    }

    /**
     * Gets the value of the hsInfo property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link HsInfo }{@code >}
     *     
     */
    public JAXBElement<HsInfo> getHsInfo() {
        return hsInfo;
    }

    /**
     * Sets the value of the hsInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link HsInfo }{@code >}
     *     
     */
    public void setHsInfo(JAXBElement<HsInfo> value) {
        this.hsInfo = ((JAXBElement<HsInfo> ) value);
    }

    /**
     * Gets the value of the interests property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public synchronized String getInterests() {
        return interests.getValue();
    }

    /**
     * Sets the value of the interests property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setInterests(JAXBElement<String> value) {
        this.interests = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the isAppUser property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsAppUser() {
        return isAppUser;
    }

    /**
     * Sets the value of the isAppUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsAppUser(Boolean value) {
        this.isAppUser = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the meetingFor property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link User.MeetingFor }{@code >}
     *     
     */
    public JAXBElement<User.MeetingFor> getMeetingFor() {
        return meetingFor;
    }

    /**
     * Sets the value of the meetingFor property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link User.MeetingFor }{@code >}
     *     
     */
    public void setMeetingFor(JAXBElement<User.MeetingFor> value) {
        this.meetingFor = ((JAXBElement<User.MeetingFor> ) value);
    }

    /**
     * Gets the value of the meetingSex property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link User.MeetingSex }{@code >}
     *     
     */
    public JAXBElement<User.MeetingSex> getMeetingSex() {
        return meetingSex;
    }

    /**
     * Sets the value of the meetingSex property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link User.MeetingSex }{@code >}
     *     
     */
    public void setMeetingSex(JAXBElement<User.MeetingSex> value) {
        this.meetingSex = ((JAXBElement<User.MeetingSex> ) value);
    }

    /**
     * Gets the value of the movies property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public synchronized String getMovies() {
        return movies.getValue();
    }

    /**
     * Sets the value of the movies property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setMovies(JAXBElement<String> value) {
        this.movies = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the music property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public synchronized String getMusic() {
        return music.getValue();
    }

    /**
     * Sets the value of the music property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setMusic(JAXBElement<String> value) {
        this.music = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the notesCount property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getNotesCount() {
        return notesCount;
    }

    /**
     * Sets the value of the notesCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setNotesCount(JAXBElement<Integer> value) {
        this.notesCount = ((JAXBElement<Integer> ) value);
    }

    /**
     * Gets the value of the pic property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public synchronized String getPic() {
        return pic.getValue();
    }

    /**
     * Sets the value of the pic property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPic(JAXBElement<String> value) {
        this.pic = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the picBig property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public synchronized String getPicBig() {
        return picBig.getValue();
    }

    /**
     * Sets the value of the picBig property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPicBig(JAXBElement<String> value) {
        this.picBig = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the picSmall property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public synchronized String getPicSmall() {
        return picSmall.getValue();
    }

    /**
     * Sets the value of the picSmall property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPicSmall(JAXBElement<String> value) {
        this.picSmall = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the political property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public synchronized String getPolitical() {
        return political.getValue();
    }

    /**
     * Sets the value of the political property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPolitical(JAXBElement<String> value) {
        this.political = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the profileUpdateTime property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public synchronized Integer getProfileUpdateTime() {
        return profileUpdateTime.getValue();
    }

    /**
     * Sets the value of the profileUpdateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setProfileUpdateTime(JAXBElement<Integer> value) {
        this.profileUpdateTime = ((JAXBElement<Integer> ) value);
    }

    /**
     * Gets the value of the quotes property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public synchronized String getQuotes() {
        return quotes.getValue();
    }

    /**
     * Sets the value of the quotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setQuotes(JAXBElement<String> value) {
        this.quotes = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the relationshipStatus property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public synchronized String getRelationshipStatus() {
        return relationshipStatus.getValue();
    }

    /**
     * Sets the value of the relationshipStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRelationshipStatus(JAXBElement<String> value) {
        this.relationshipStatus = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the religion property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public synchronized String getReligion() {
        return religion.getValue();
    }

    /**
     * Sets the value of the religion property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setReligion(JAXBElement<String> value) {
        this.religion = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the sex property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public synchronized String getSex() {
        return sex.getValue();
    }

    /**
     * Sets the value of the sex property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSex(JAXBElement<String> value) {
        this.sex = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the significantOtherId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public synchronized Long getSignificantOtherId() {
        return significantOtherId.getValue();
    }

    /**
     * Sets the value of the significantOtherId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setSignificantOtherId(JAXBElement<Long> value) {
        this.significantOtherId = ((JAXBElement<Long> ) value);
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link UserStatus }{@code >}
     *     
     */
    public JAXBElement<UserStatus> getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link UserStatus }{@code >}
     *     
     */
    public void setStatus(JAXBElement<UserStatus> value) {
        this.status = ((JAXBElement<UserStatus> ) value);
    }

    /**
     * Gets the value of the timezone property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getTimezone() {
        return timezone;
    }

    /**
     * Sets the value of the timezone property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setTimezone(JAXBElement<BigDecimal> value) {
        this.timezone = ((JAXBElement<BigDecimal> ) value);
    }

    /**
     * Gets the value of the tv property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public synchronized String getTv() {
        return tv.getValue();
    }

    /**
     * Sets the value of the tv property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTv(JAXBElement<String> value) {
        this.tv = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the uid property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Long getUid() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setUid(Long value) {
        this.uid = value;
    }

    /**
     * Gets the value of the wallCount property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public synchronized Integer getWallCount() {
        return wallCount.getValue();
    }

    /**
     * Sets the value of the wallCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setWallCount(JAXBElement<Integer> value) {
        this.wallCount = ((JAXBElement<Integer> ) value);
    }

    /**
     * Gets the value of the workHistory property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link User.WorkHistory }{@code >}
     *     
     */
    public JAXBElement<User.WorkHistory> getWorkHistory() {
        return workHistory;
    }

    /**
     * Sets the value of the workHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link User.WorkHistory }{@code >}
     *     
     */
    public void setWorkHistory(JAXBElement<User.WorkHistory> value) {
        this.workHistory = ((JAXBElement<User.WorkHistory> ) value);
    }

    /**
     * Gets the value of the picSquare property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public synchronized String getPicSquare() {
        return picSquare.getValue();
    }

    /**
     * Sets the value of the picSquare property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPicSquare(JAXBElement<String> value) {
        this.picSquare = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the hasAddedApp property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     *     
     */
    public Boolean getHasAddedApp() {
        return hasAddedApp.getValue();
    }

    /**
     * Sets the value of the hasAddedApp property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     *     
     */
    public void setHasAddedApp(JAXBElement<Boolean> value) {
        this.hasAddedApp = ((JAXBElement<Boolean> ) value);
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="affiliation" type="{http://api.facebook.com/1.0/}affiliation" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "affiliation"
    })
    public static class Affiliations {

        protected List<Affiliation> affiliation;
        @XmlAttribute
        protected Boolean list;

        /**
         * Gets the value of the affiliation property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the affiliation property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAffiliation().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Affiliation }
         * 
         * 
         */
        public List<Affiliation> getAffiliation() {
            if (affiliation == null) {
                affiliation = new ArrayList<Affiliation>();
            }
            return this.affiliation;
        }

        /**
         * Gets the value of the list property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isList() {
            return list;
        }

        /**
         * Sets the value of the list property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setList(Boolean value) {
            this.list = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="education_info" type="{http://api.facebook.com/1.0/}education_info" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "educationInfo"
    })
    public static class EducationHistory {

        @XmlElement(name = "education_info")
        protected List<EducationInfo> educationInfo;
        @XmlAttribute
        protected Boolean list;

        /**
         * Gets the value of the educationInfo property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the educationInfo property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEducationInfo().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EducationInfo }
         * 
         * 
         */
        public List<EducationInfo> getEducationInfo() {
            if (educationInfo == null) {
                educationInfo = new ArrayList<EducationInfo>();
            }
            return this.educationInfo;
        }

        /**
         * Gets the value of the list property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isList() {
            return list;
        }

        /**
         * Sets the value of the list property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setList(Boolean value) {
            this.list = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="seeking" type="{http://api.facebook.com/1.0/}seeking" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "seeking"
    })
    public static class MeetingFor {

        protected List<String> seeking;
        @XmlAttribute
        protected Boolean list;

        /**
         * Gets the value of the seeking property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the seeking property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSeeking().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getSeeking() {
            if (seeking == null) {
                seeking = new ArrayList<String>();
            }
            return this.seeking;
        }

        /**
         * Gets the value of the list property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isList() {
            return list;
        }

        /**
         * Sets the value of the list property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setList(Boolean value) {
            this.list = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="sex" type="{http://api.facebook.com/1.0/}sex" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sex"
    })
    public static class MeetingSex {

        protected List<String> sex;
        @XmlAttribute
        protected Boolean list;

        /**
         * Gets the value of the sex property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the sex property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSex().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getSex() {
            if (sex == null) {
                sex = new ArrayList<String>();
            }
            return this.sex;
        }

        /**
         * Gets the value of the list property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isList() {
            return list;
        }

        /**
         * Sets the value of the list property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setList(Boolean value) {
            this.list = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="work_info" type="{http://api.facebook.com/1.0/}work_info" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "workInfo"
    })
    public static class WorkHistory {

        @XmlElement(name = "work_info")
        protected List<WorkInfo> workInfo;
        @XmlAttribute
        protected Boolean list;

        /**
         * Gets the value of the workInfo property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the workInfo property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getWorkInfo().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link WorkInfo }
         * 
         * 
         */
        public List<WorkInfo> getWorkInfo() {
            if (workInfo == null) {
                workInfo = new ArrayList<WorkInfo>();
            }
            return this.workInfo;
        }

        /**
         * Gets the value of the list property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isList() {
            return list;
        }

        /**
         * Sets the value of the list property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setList(Boolean value) {
            this.list = value;
        }

    }

}
