//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.06.20 at 06:10:07 PM HST 
//


package com.facebook.api.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for friend_info complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="friend_info">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="uid1" type="{http://api.facebook.com/1.0/}uid" minOccurs="0"/>
 *         &lt;element name="uid2" type="{http://api.facebook.com/1.0/}uid" minOccurs="0"/>
 *         &lt;element name="are_friends" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "friend_info", propOrder = {

})
public class FriendInfo {

    protected Long uid1;
    protected Long uid2;
    @XmlElementRef(name = "are_friends", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<Boolean> areFriends;

    /**
     * Gets the value of the uid1 property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public synchronized Long getUid1() {
        return uid1;
    }

    /**
     * Sets the value of the uid1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public synchronized void setUid1(Long value) {
        this.uid1 = value;
    }

    /**
     * Gets the value of the uid2 property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public synchronized Long getUid2() {
        return uid2;
    }

    /**
     * Sets the value of the uid2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public synchronized void setUid2(Long value) {
        this.uid2 = value;
    }

    /**
     * Gets the value of the areFriends property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     *     
     */
    public synchronized JAXBElement<Boolean> getAreFriends() {
        return areFriends;
    }

    /**
     * Sets the value of the areFriends property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     *     
     */
    public synchronized void setAreFriends(JAXBElement<Boolean> value) {
        this.areFriends = value;
    }

}
