//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.06.20 at 06:10:07 PM HST 
//


package com.facebook.api.schema;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for notifications complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="notifications">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="messages" type="{http://api.facebook.com/1.0/}notification_count"/>
 *         &lt;element name="pokes" type="{http://api.facebook.com/1.0/}notification_count"/>
 *         &lt;element name="shares" type="{http://api.facebook.com/1.0/}notification_count"/>
 *         &lt;element name="friend_requests">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="uid" type="{http://api.facebook.com/1.0/}uid" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="group_invites">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="gid" type="{http://api.facebook.com/1.0/}gid" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="event_invites">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="eid" type="{http://api.facebook.com/1.0/}eid" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "notifications", propOrder = {
    "messages",
    "pokes",
    "shares",
    "friendRequests",
    "groupInvites",
    "eventInvites"
})
public class Notifications {

    @XmlElement(required = true)
    protected NotificationCount messages;
    @XmlElement(required = true)
    protected NotificationCount pokes;
    @XmlElement(required = true)
    protected NotificationCount shares;
    @XmlElement(name = "friend_requests", required = true)
    protected Notifications.FriendRequests friendRequests;
    @XmlElement(name = "group_invites", required = true)
    protected Notifications.GroupInvites groupInvites;
    @XmlElement(name = "event_invites", required = true)
    protected Notifications.EventInvites eventInvites;

    /**
     * Gets the value of the messages property.
     * 
     * @return
     *     possible object is
     *     {@link NotificationCount }
     *     
     */
    public synchronized NotificationCount getMessages() {
        return messages;
    }

    /**
     * Sets the value of the messages property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotificationCount }
     *     
     */
    public synchronized void setMessages(NotificationCount value) {
        this.messages = value;
    }

    /**
     * Gets the value of the pokes property.
     * 
     * @return
     *     possible object is
     *     {@link NotificationCount }
     *     
     */
    public synchronized NotificationCount getPokes() {
        return pokes;
    }

    /**
     * Sets the value of the pokes property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotificationCount }
     *     
     */
    public synchronized void setPokes(NotificationCount value) {
        this.pokes = value;
    }

    /**
     * Gets the value of the shares property.
     * 
     * @return
     *     possible object is
     *     {@link NotificationCount }
     *     
     */
    public synchronized NotificationCount getShares() {
        return shares;
    }

    /**
     * Sets the value of the shares property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotificationCount }
     *     
     */
    public synchronized void setShares(NotificationCount value) {
        this.shares = value;
    }

    /**
     * Gets the value of the friendRequests property.
     * 
     * @return
     *     possible object is
     *     {@link Notifications.FriendRequests }
     *     
     */
    public synchronized Notifications.FriendRequests getFriendRequests() {
        return friendRequests;
    }

    /**
     * Sets the value of the friendRequests property.
     * 
     * @param value
     *     allowed object is
     *     {@link Notifications.FriendRequests }
     *     
     */
    public synchronized void setFriendRequests(Notifications.FriendRequests value) {
        this.friendRequests = value;
    }

    /**
     * Gets the value of the groupInvites property.
     * 
     * @return
     *     possible object is
     *     {@link Notifications.GroupInvites }
     *     
     */
    public synchronized Notifications.GroupInvites getGroupInvites() {
        return groupInvites;
    }

    /**
     * Sets the value of the groupInvites property.
     * 
     * @param value
     *     allowed object is
     *     {@link Notifications.GroupInvites }
     *     
     */
    public synchronized void setGroupInvites(Notifications.GroupInvites value) {
        this.groupInvites = value;
    }

    /**
     * Gets the value of the eventInvites property.
     * 
     * @return
     *     possible object is
     *     {@link Notifications.EventInvites }
     *     
     */
    public synchronized Notifications.EventInvites getEventInvites() {
        return eventInvites;
    }

    /**
     * Sets the value of the eventInvites property.
     * 
     * @param value
     *     allowed object is
     *     {@link Notifications.EventInvites }
     *     
     */
    public synchronized void setEventInvites(Notifications.EventInvites value) {
        this.eventInvites = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="eid" type="{http://api.facebook.com/1.0/}eid" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "eid"
    })
    public static class EventInvites {

        @XmlElement(type = Long.class)
        protected List<Long> eid;
        @XmlAttribute
        protected Boolean list;

        /**
         * Gets the value of the eid property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the eid property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEid().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Long }
         * 
         * 
         */
        public synchronized List<Long> getEid() {
            if (eid == null) {
                eid = new ArrayList<Long>();
            }
            return this.eid;
        }

        /**
         * Gets the value of the list property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public synchronized Boolean isList() {
            return list;
        }

        /**
         * Sets the value of the list property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public synchronized void setList(Boolean value) {
            this.list = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="uid" type="{http://api.facebook.com/1.0/}uid" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "uid"
    })
    public static class FriendRequests {

        @XmlElement(type = Long.class)
        protected List<Long> uid;
        @XmlAttribute
        protected Boolean list;

        /**
         * Gets the value of the uid property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the uid property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUid().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Long }
         * 
         * 
         */
        public synchronized List<Long> getUid() {
            if (uid == null) {
                uid = new ArrayList<Long>();
            }
            return this.uid;
        }

        /**
         * Gets the value of the list property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public synchronized Boolean isList() {
            return list;
        }

        /**
         * Sets the value of the list property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public synchronized void setList(Boolean value) {
            this.list = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="gid" type="{http://api.facebook.com/1.0/}gid" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "gid"
    })
    public static class GroupInvites {

        @XmlElement(type = Long.class)
        protected List<Long> gid;
        @XmlAttribute
        protected Boolean list;

        /**
         * Gets the value of the gid property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the gid property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGid().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Long }
         * 
         * 
         */
        public synchronized List<Long> getGid() {
            if (gid == null) {
                gid = new ArrayList<Long>();
            }
            return this.gid;
        }

        /**
         * Gets the value of the list property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public synchronized Boolean isList() {
            return list;
        }

        /**
         * Sets the value of the list property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public synchronized void setList(Boolean value) {
            this.list = value;
        }

    }

}
