//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.06.20 at 06:10:07 PM HST 
//


package com.facebook.api.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for session_info complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="session_info">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="session_key" type="{http://api.facebook.com/1.0/}session_key"/>
 *         &lt;element name="uid" type="{http://api.facebook.com/1.0/}uid"/>
 *         &lt;element name="expires" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="secret" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "session_info", propOrder = {
    "sessionKey",
    "uid",
    "expires",
    "secret"
})
public class SessionInfo {

    @XmlElement(name = "session_key", required = true)
    protected String sessionKey;
    protected long uid;
    protected int expires;
    protected String secret;

    /**
     * Gets the value of the sessionKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public synchronized String getSessionKey() {
        return sessionKey;
    }

    /**
     * Sets the value of the sessionKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public synchronized void setSessionKey(String value) {
        this.sessionKey = value;
    }

    /**
     * Gets the value of the uid property.
     * 
     */
    public synchronized long getUid() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     * 
     */
    public synchronized void setUid(long value) {
        this.uid = value;
    }

    /**
     * Gets the value of the expires property.
     * 
     */
    public synchronized int getExpires() {
        return expires;
    }

    /**
     * Sets the value of the expires property.
     * 
     */
    public synchronized void setExpires(int value) {
        this.expires = value;
    }

    /**
     * Gets the value of the secret property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public synchronized String getSecret() {
        return secret;
    }

    /**
     * Sets the value of the secret property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public synchronized void setSecret(String value) {
        this.secret = value;
    }

}
