//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.06.20 at 06:10:07 PM HST 
//


package com.facebook.api.schema;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for group_members complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="group_members">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="members">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="uid" type="{http://api.facebook.com/1.0/}uid" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="admins">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="uid" type="{http://api.facebook.com/1.0/}uid" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="officers">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="uid" type="{http://api.facebook.com/1.0/}uid" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="not_replied">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="uid" type="{http://api.facebook.com/1.0/}uid" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "group_members", propOrder = {
    "members",
    "admins",
    "officers",
    "notReplied"
})
public class GroupMembers {

    @XmlElement(required = true)
    protected GroupMembers.Members members;
    @XmlElement(required = true)
    protected GroupMembers.Admins admins;
    @XmlElement(required = true)
    protected GroupMembers.Officers officers;
    @XmlElement(name = "not_replied", required = true)
    protected GroupMembers.NotReplied notReplied;

    /**
     * Gets the value of the members property.
     * 
     * @return
     *     possible object is
     *     {@link GroupMembers.Members }
     *     
     */
    public synchronized GroupMembers.Members getMembers() {
        return members;
    }

    /**
     * Sets the value of the members property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupMembers.Members }
     *     
     */
    public synchronized void setMembers(GroupMembers.Members value) {
        this.members = value;
    }

    /**
     * Gets the value of the admins property.
     * 
     * @return
     *     possible object is
     *     {@link GroupMembers.Admins }
     *     
     */
    public synchronized GroupMembers.Admins getAdmins() {
        return admins;
    }

    /**
     * Sets the value of the admins property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupMembers.Admins }
     *     
     */
    public synchronized void setAdmins(GroupMembers.Admins value) {
        this.admins = value;
    }

    /**
     * Gets the value of the officers property.
     * 
     * @return
     *     possible object is
     *     {@link GroupMembers.Officers }
     *     
     */
    public synchronized GroupMembers.Officers getOfficers() {
        return officers;
    }

    /**
     * Sets the value of the officers property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupMembers.Officers }
     *     
     */
    public synchronized void setOfficers(GroupMembers.Officers value) {
        this.officers = value;
    }

    /**
     * Gets the value of the notReplied property.
     * 
     * @return
     *     possible object is
     *     {@link GroupMembers.NotReplied }
     *     
     */
    public synchronized GroupMembers.NotReplied getNotReplied() {
        return notReplied;
    }

    /**
     * Sets the value of the notReplied property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupMembers.NotReplied }
     *     
     */
    public synchronized void setNotReplied(GroupMembers.NotReplied value) {
        this.notReplied = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="uid" type="{http://api.facebook.com/1.0/}uid" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "uid"
    })
    public static class Admins {

        @XmlElement(type = Integer.class)
        protected List<Long> uid;
        @XmlAttribute
        protected Boolean list;

        /**
         * Gets the value of the uid property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the uid property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUid().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Long }
         * 
         * 
         */
        public synchronized List<Long> getUid() {
            if (uid == null) {
                uid = new ArrayList<Long>();
            }
            return this.uid;
        }

        /**
         * Gets the value of the list property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public synchronized Boolean isList() {
            return list;
        }

        /**
         * Sets the value of the list property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public synchronized void setList(Boolean value) {
            this.list = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="uid" type="{http://api.facebook.com/1.0/}uid" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "uid"
    })
    public static class Members {

        @XmlElement(type = Long.class)
        protected List<Long> uid;
        @XmlAttribute
        protected Boolean list;

        /**
         * Gets the value of the uid property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the uid property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUid().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Long }
         * 
         * 
         */
        public synchronized List<Long> getUid() {
            if (uid == null) {
                uid = new ArrayList<Long>();
            }
            return this.uid;
        }

        /**
         * Gets the value of the list property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public synchronized Boolean isList() {
            return list;
        }

        /**
         * Sets the value of the list property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public synchronized void setList(Boolean value) {
            this.list = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="uid" type="{http://api.facebook.com/1.0/}uid" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "uid"
    })
    public static class NotReplied {

        @XmlElement(type = Long.class)
        protected List<Long> uid;
        @XmlAttribute
        protected Boolean list;

        /**
         * Gets the value of the uid property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the uid property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUid().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Long }
         * 
         * 
         */
        public synchronized List<Long> getUid() {
            if (uid == null) {
                uid = new ArrayList<Long>();
            }
            return this.uid;
        }

        /**
         * Gets the value of the list property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public synchronized Boolean isList() {
            return list;
        }

        /**
         * Sets the value of the list property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public synchronized void setList(Boolean value) {
            this.list = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="uid" type="{http://api.facebook.com/1.0/}uid" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "uid"
    })
    public static class Officers {

        @XmlElement(type = Long.class)
        protected List<Long> uid;
        @XmlAttribute
        protected Boolean list;

        /**
         * Gets the value of the uid property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the uid property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUid().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Long }
         * 
         * 
         */
        public synchronized List<Long> getUid() {
            if (uid == null) {
                uid = new ArrayList<Long>();
            }
            return this.uid;
        }

        /**
         * Gets the value of the list property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public synchronized Boolean isList() {
            return list;
        }

        /**
         * Sets the value of the list property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public synchronized void setList(Boolean value) {
            this.list = value;
        }

    }

}
