//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.06.20 at 06:10:07 PM HST 
//


package com.facebook.api.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for album complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="album">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="aid" type="{http://api.facebook.com/1.0/}aid"/>
 *         &lt;element name="cover_pid" type="{http://api.facebook.com/1.0/}pid"/>
 *         &lt;element name="owner" type="{http://api.facebook.com/1.0/}uid"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="created" type="{http://api.facebook.com/1.0/}time"/>
 *         &lt;element name="modified" type="{http://api.facebook.com/1.0/}time"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="size" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "album", propOrder = {
    "aid",
    "coverPid",
    "owner",
    "name",
    "created",
    "modified",
    "description",
    "location",
    "link",
    "size"
})
public class Album {

    protected long aid;
    @XmlElement(name = "cover_pid")
    protected long coverPid;
    protected long owner;
    @XmlElement(required = true)
    protected String name;
    protected int created;
    protected int modified;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected String location;
    @XmlElement(required = true)
    protected String link;
    protected int size;

    /**
     * Gets the value of the aid property.
     * 
     */
    public synchronized long getAid() {
        return aid;
    }

    /**
     * Sets the value of the aid property.
     * 
     */
    public synchronized void setAid(long value) {
        this.aid = value;
    }

    /**
     * Gets the value of the coverPid property.
     * 
     */
    public synchronized long getCoverPid() {
        return coverPid;
    }

    /**
     * Sets the value of the coverPid property.
     * 
     */
    public synchronized void setCoverPid(long value) {
        this.coverPid = value;
    }

    /**
     * Gets the value of the owner property.
     * 
     */
    public synchronized long getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     */
    public synchronized void setOwner(long value) {
        this.owner = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public synchronized String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public synchronized void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the created property.
     * 
     */
    public synchronized int getCreated() {
        return created;
    }

    /**
     * Sets the value of the created property.
     * 
     */
    public synchronized void setCreated(int value) {
        this.created = value;
    }

    /**
     * Gets the value of the modified property.
     * 
     */
    public synchronized int getModified() {
        return modified;
    }

    /**
     * Sets the value of the modified property.
     * 
     */
    public synchronized void setModified(int value) {
        this.modified = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public synchronized String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public synchronized void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public synchronized String getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public synchronized void setLocation(String value) {
        this.location = value;
    }

    /**
     * Gets the value of the link property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public synchronized String getLink() {
        return link;
    }

    /**
     * Sets the value of the link property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public synchronized void setLink(String value) {
        this.link = value;
    }

    /**
     * Gets the value of the size property.
     * 
     */
    public synchronized int getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     */
    public synchronized void setSize(int value) {
        this.size = value;
    }

}
