//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.08 at 04:00:59 PM PDT 
//


package com.facebook.api.schema;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for app_info complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="app_info">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="app_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="api_key" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="canvas_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="display_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="icon_url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="logo_url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="developers">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="developer_info" type="{http://api.facebook.com/1.0/}developer_info" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="company_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="daily_active_users" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="daily_active_percentage" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "app_info", propOrder = {
    "appId",
    "apiKey",
    "canvasName",
    "displayName",
    "iconUrl",
    "logoUrl",
    "developers",
    "companyName",
    "description",
    "dailyActiveUsers",
    "dailyActivePercentage"
})
public class AppInfo {

    @XmlElement(name = "app_id")
    protected long appId;
    @XmlElement(name = "api_key", required = true)
    protected String apiKey;
    @XmlElement(name = "canvas_name", required = true)
    protected String canvasName;
    @XmlElement(name = "display_name", required = true)
    protected String displayName;
    @XmlElement(name = "icon_url", required = true)
    protected String iconUrl;
    @XmlElement(name = "logo_url", required = true)
    protected String logoUrl;
    @XmlElement(required = true)
    protected AppInfo.Developers developers;
    @XmlElement(name = "company_name", required = true)
    protected String companyName;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(name = "daily_active_users")
    protected int dailyActiveUsers;
    @XmlElement(name = "daily_active_percentage")
    protected int dailyActivePercentage;

    /**
     * Gets the value of the appId property.
     * 
     */
    public long getAppId() {
        return appId;
    }

    /**
     * Sets the value of the appId property.
     * 
     */
    public void setAppId(long value) {
        this.appId = value;
    }

    /**
     * Gets the value of the apiKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApiKey() {
        return apiKey;
    }

    /**
     * Sets the value of the apiKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApiKey(String value) {
        this.apiKey = value;
    }

    /**
     * Gets the value of the canvasName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCanvasName() {
        return canvasName;
    }

    /**
     * Sets the value of the canvasName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCanvasName(String value) {
        this.canvasName = value;
    }

    /**
     * Gets the value of the displayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the iconUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIconUrl() {
        return iconUrl;
    }

    /**
     * Sets the value of the iconUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIconUrl(String value) {
        this.iconUrl = value;
    }

    /**
     * Gets the value of the logoUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogoUrl() {
        return logoUrl;
    }

    /**
     * Sets the value of the logoUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogoUrl(String value) {
        this.logoUrl = value;
    }

    /**
     * Gets the value of the developers property.
     * 
     * @return
     *     possible object is
     *     {@link AppInfo.Developers }
     *     
     */
    public AppInfo.Developers getDevelopers() {
        return developers;
    }

    /**
     * Sets the value of the developers property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppInfo.Developers }
     *     
     */
    public void setDevelopers(AppInfo.Developers value) {
        this.developers = value;
    }

    /**
     * Gets the value of the companyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * Sets the value of the companyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyName(String value) {
        this.companyName = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the dailyActiveUsers property.
     * 
     */
    public int getDailyActiveUsers() {
        return dailyActiveUsers;
    }

    /**
     * Sets the value of the dailyActiveUsers property.
     * 
     */
    public void setDailyActiveUsers(int value) {
        this.dailyActiveUsers = value;
    }

    /**
     * Gets the value of the dailyActivePercentage property.
     * 
     */
    public int getDailyActivePercentage() {
        return dailyActivePercentage;
    }

    /**
     * Sets the value of the dailyActivePercentage property.
     * 
     */
    public void setDailyActivePercentage(int value) {
        this.dailyActivePercentage = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="developer_info" type="{http://api.facebook.com/1.0/}developer_info" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "developerInfo"
    })
    public static class Developers {

        @XmlElement(name = "developer_info")
        protected List<DeveloperInfo> developerInfo;
        @XmlAttribute
        protected Boolean list;

        /**
         * Gets the value of the developerInfo property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the developerInfo property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDeveloperInfo().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DeveloperInfo }
         * 
         * 
         */
        public List<DeveloperInfo> getDeveloperInfo() {
            if (developerInfo == null) {
                developerInfo = new ArrayList<DeveloperInfo>();
            }
            return this.developerInfo;
        }

        /**
         * Gets the value of the list property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isList() {
            return list;
        }

        /**
         * Sets the value of the list property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setList(Boolean value) {
            this.list = value;
        }

    }

}
