//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.06.20 at 06:10:07 PM HST 
//


package com.facebook.api.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for notification_count complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="notification_count">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="unread" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="most_recent" type="{http://api.facebook.com/1.0/}time"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "notification_count", propOrder = {
    "unread",
    "mostRecent"
})
public class NotificationCount {

    protected int unread;
    @XmlElement(name = "most_recent")
    protected int mostRecent;

    /**
     * Gets the value of the unread property.
     * 
     */
    public synchronized int getUnread() {
        return unread;
    }

    /**
     * Sets the value of the unread property.
     * 
     */
    public synchronized void setUnread(int value) {
        this.unread = value;
    }

    /**
     * Gets the value of the mostRecent property.
     * 
     */
    public synchronized int getMostRecent() {
        return mostRecent;
    }

    /**
     * Sets the value of the mostRecent property.
     * 
     */
    public synchronized void setMostRecent(int value) {
        this.mostRecent = value;
    }

}
