//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.06.20 at 06:10:07 PM HST 
//


package com.facebook.api.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for photo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="photo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pid" type="{http://api.facebook.com/1.0/}pid"/>
 *         &lt;element name="aid" type="{http://api.facebook.com/1.0/}aid"/>
 *         &lt;element name="owner" type="{http://api.facebook.com/1.0/}uid"/>
 *         &lt;element name="src" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="src_big" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="src_small" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="caption" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="created" type="{http://api.facebook.com/1.0/}time"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "photo", propOrder = {
    "pid",
    "aid",
    "owner",
    "src",
    "srcBig",
    "srcSmall",
    "link",
    "caption",
    "created"
})
public class Photo {

    protected long pid;
    protected long aid;
    protected long owner;
    @XmlElement(required = true)
    protected String src;
    @XmlElement(name = "src_big", required = true)
    protected String srcBig;
    @XmlElement(name = "src_small", required = true)
    protected String srcSmall;
    @XmlElement(required = true)
    protected String link;
    @XmlElement(required = true)
    protected String caption;
    protected int created;

    /**
     * Gets the value of the pid property.
     * 
     */
    public synchronized long getPid() {
        return pid;
    }

    /**
     * Sets the value of the pid property.
     * 
     */
    public synchronized void setPid(long value) {
        this.pid = value;
    }

    /**
     * Gets the value of the aid property.
     * 
     */
    public synchronized long getAid() {
        return aid;
    }

    /**
     * Sets the value of the aid property.
     * 
     */
    public synchronized void setAid(long value) {
        this.aid = value;
    }

    /**
     * Gets the value of the owner property.
     * 
     */
    public synchronized long getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     */
    public synchronized void setOwner(long value) {
        this.owner = value;
    }

    /**
     * Gets the value of the src property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public synchronized String getSrc() {
        return src;
    }

    /**
     * Sets the value of the src property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public synchronized void setSrc(String value) {
        this.src = value;
    }

    /**
     * Gets the value of the srcBig property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public synchronized String getSrcBig() {
        return srcBig;
    }

    /**
     * Sets the value of the srcBig property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public synchronized void setSrcBig(String value) {
        this.srcBig = value;
    }

    /**
     * Gets the value of the srcSmall property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public synchronized String getSrcSmall() {
        return srcSmall;
    }

    /**
     * Sets the value of the srcSmall property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public synchronized void setSrcSmall(String value) {
        this.srcSmall = value;
    }

    /**
     * Gets the value of the link property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public synchronized String getLink() {
        return link;
    }

    /**
     * Sets the value of the link property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public synchronized void setLink(String value) {
        this.link = value;
    }

    /**
     * Gets the value of the caption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public synchronized String getCaption() {
        return caption;
    }

    /**
     * Sets the value of the caption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public synchronized void setCaption(String value) {
        this.caption = value;
    }

    /**
     * Gets the value of the created property.
     * 
     */
    public synchronized int getCreated() {
        return created;
    }

    /**
     * Sets the value of the created property.
     * 
     */
    public synchronized void setCreated(int value) {
        this.created = value;
    }

}
