//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.06.20 at 06:10:07 PM HST 
//


package com.facebook.api.schema;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for event_members complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="event_members">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="attending">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="uid" type="{http://api.facebook.com/1.0/}uid" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="unsure">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="uid" type="{http://api.facebook.com/1.0/}uid" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="declined">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="uid" type="{http://api.facebook.com/1.0/}uid" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="not_replied">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="uid" type="{http://api.facebook.com/1.0/}uid" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "event_members", propOrder = {
    "attending",
    "unsure",
    "declined",
    "notReplied"
})
public class EventMembers {

    @XmlElement(required = true)
    protected EventMembers.Attending attending;
    @XmlElement(required = true)
    protected EventMembers.Unsure unsure;
    @XmlElement(required = true)
    protected EventMembers.Declined declined;
    @XmlElement(name = "not_replied", required = true)
    protected EventMembers.NotReplied notReplied;

    /**
     * Gets the value of the attending property.
     * 
     * @return
     *     possible object is
     *     {@link EventMembers.Attending }
     *     
     */
    public synchronized EventMembers.Attending getAttending() {
        return attending;
    }

    /**
     * Sets the value of the attending property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventMembers.Attending }
     *     
     */
    public synchronized void setAttending(EventMembers.Attending value) {
        this.attending = value;
    }

    /**
     * Gets the value of the unsure property.
     * 
     * @return
     *     possible object is
     *     {@link EventMembers.Unsure }
     *     
     */
    public synchronized EventMembers.Unsure getUnsure() {
        return unsure;
    }

    /**
     * Sets the value of the unsure property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventMembers.Unsure }
     *     
     */
    public synchronized void setUnsure(EventMembers.Unsure value) {
        this.unsure = value;
    }

    /**
     * Gets the value of the declined property.
     * 
     * @return
     *     possible object is
     *     {@link EventMembers.Declined }
     *     
     */
    public synchronized EventMembers.Declined getDeclined() {
        return declined;
    }

    /**
     * Sets the value of the declined property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventMembers.Declined }
     *     
     */
    public synchronized void setDeclined(EventMembers.Declined value) {
        this.declined = value;
    }

    /**
     * Gets the value of the notReplied property.
     * 
     * @return
     *     possible object is
     *     {@link EventMembers.NotReplied }
     *     
     */
    public synchronized EventMembers.NotReplied getNotReplied() {
        return notReplied;
    }

    /**
     * Sets the value of the notReplied property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventMembers.NotReplied }
     *     
     */
    public synchronized void setNotReplied(EventMembers.NotReplied value) {
        this.notReplied = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="uid" type="{http://api.facebook.com/1.0/}uid" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "uid"
    })
    public static class Attending {

        @XmlElement(type = Long.class)
        protected List<Long> uid;
        @XmlAttribute
        protected Boolean list;

        /**
         * Gets the value of the uid property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the uid property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUid().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Integer }
         * 
         * 
         */
        public synchronized List<Long> getUid() {
            if (uid == null) {
                uid = new ArrayList<Long>();
            }
            return this.uid;
        }

        /**
         * Gets the value of the list property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public synchronized Boolean isList() {
            return list;
        }

        /**
         * Sets the value of the list property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public synchronized void setList(Boolean value) {
            this.list = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="uid" type="{http://api.facebook.com/1.0/}uid" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "uid"
    })
    public static class Declined {

        @XmlElement(type = Long.class)
        protected List<Long> uid;
        @XmlAttribute
        protected Boolean list;

        /**
         * Gets the value of the uid property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the uid property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUid().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Integer }
         * 
         * 
         */
        public synchronized List<Long> getUid() {
            if (uid == null) {
                uid = new ArrayList<Long>();
            }
            return this.uid;
        }

        /**
         * Gets the value of the list property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public synchronized Boolean isList() {
            return list;
        }

        /**
         * Sets the value of the list property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public synchronized void setList(Boolean value) {
            this.list = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="uid" type="{http://api.facebook.com/1.0/}uid" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "uid"
    })
    public static class NotReplied {

        @XmlElement(type = Long.class)
        protected List<Long> uid;
        @XmlAttribute
        protected Boolean list;

        /**
         * Gets the value of the uid property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the uid property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUid().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Integer }
         * 
         * 
         */
        public synchronized List<Long> getUid() {
            if (uid == null) {
                uid = new ArrayList<Long>();
            }
            return this.uid;
        }

        /**
         * Gets the value of the list property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public synchronized Boolean isList() {
            return list;
        }

        /**
         * Sets the value of the list property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public synchronized void setList(Boolean value) {
            this.list = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="uid" type="{http://api.facebook.com/1.0/}uid" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "uid"
    })
    public static class Unsure {

        @XmlElement(type = Long.class)
        protected List<Long> uid;
        @XmlAttribute
        protected Boolean list;

        /**
         * Gets the value of the uid property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the uid property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUid().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Integer }
         * 
         * 
         */
        public synchronized List<Long> getUid() {
            if (uid == null) {
                uid = new ArrayList<Long>();
            }
            return this.uid;
        }

        /**
         * Gets the value of the list property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public synchronized Boolean isList() {
            return list;
        }

        /**
         * Sets the value of the list property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public synchronized void setList(Boolean value) {
            this.list = value;
        }

    }

}
