//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.07.20 at 05:29:33 PM PDT 
//


package com.facebook.api.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for full_story_template complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="full_story_template">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="template_title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="template_body" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "full_story_template", propOrder = {
    "templateTitle",
    "templateBody"
})
public class FullStoryTemplate {

    @XmlElement(name = "template_title", required = true)
    protected String templateTitle;
    @XmlElement(name = "template_body", required = true)
    protected String templateBody;

    /**
     * Gets the value of the templateTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemplateTitle() {
        return templateTitle;
    }

    /**
     * Sets the value of the templateTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemplateTitle(String value) {
        this.templateTitle = value;
    }

    /**
     * Gets the value of the templateBody property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemplateBody() {
        return templateBody;
    }

    /**
     * Sets the value of the templateBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemplateBody(String value) {
        this.templateBody = value;
    }

}
