//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.10 at 10:42:34 PM PST 
//


package com.facebook.api.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for page_restaurant_specialties complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="page_restaurant_specialties">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="breakfast" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="lunch" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="dinner" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="coffee" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="drinks" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "page_restaurant_specialties", propOrder = {
    "breakfast",
    "lunch",
    "dinner",
    "coffee",
    "drinks"
})
public class PageRestaurantSpecialties {

    protected boolean breakfast;
    protected boolean lunch;
    protected boolean dinner;
    protected boolean coffee;
    protected boolean drinks;

    /**
     * Gets the value of the breakfast property.
     * 
     */
    public boolean isBreakfast() {
        return breakfast;
    }

    /**
     * Sets the value of the breakfast property.
     * 
     */
    public void setBreakfast(boolean value) {
        this.breakfast = value;
    }

    /**
     * Gets the value of the lunch property.
     * 
     */
    public boolean isLunch() {
        return lunch;
    }

    /**
     * Sets the value of the lunch property.
     * 
     */
    public void setLunch(boolean value) {
        this.lunch = value;
    }

    /**
     * Gets the value of the dinner property.
     * 
     */
    public boolean isDinner() {
        return dinner;
    }

    /**
     * Sets the value of the dinner property.
     * 
     */
    public void setDinner(boolean value) {
        this.dinner = value;
    }

    /**
     * Gets the value of the coffee property.
     * 
     */
    public boolean isCoffee() {
        return coffee;
    }

    /**
     * Sets the value of the coffee property.
     * 
     */
    public void setCoffee(boolean value) {
        this.coffee = value;
    }

    /**
     * Gets the value of the drinks property.
     * 
     */
    public boolean isDrinks() {
        return drinks;
    }

    /**
     * Sets the value of the drinks property.
     * 
     */
    public void setDrinks(boolean value) {
        this.drinks = value;
    }

}
