//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.10 at 10:42:34 PM PST 
//


package com.facebook.api.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for page_hours complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="page_hours">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mon_1_open" type="{http://api.facebook.com/1.0/}time"/>
 *         &lt;element name="mon_1_close" type="{http://api.facebook.com/1.0/}time"/>
 *         &lt;element name="tue_1_open" type="{http://api.facebook.com/1.0/}time"/>
 *         &lt;element name="tue_1_close" type="{http://api.facebook.com/1.0/}time"/>
 *         &lt;element name="wed_1_open" type="{http://api.facebook.com/1.0/}time"/>
 *         &lt;element name="thu_1_open" type="{http://api.facebook.com/1.0/}time"/>
 *         &lt;element name="thu_1_close" type="{http://api.facebook.com/1.0/}time"/>
 *         &lt;element name="fri_1_open" type="{http://api.facebook.com/1.0/}time"/>
 *         &lt;element name="fri_1_close" type="{http://api.facebook.com/1.0/}time"/>
 *         &lt;element name="sat_1_open" type="{http://api.facebook.com/1.0/}time"/>
 *         &lt;element name="sat_1_close" type="{http://api.facebook.com/1.0/}time"/>
 *         &lt;element name="sun_1_open" type="{http://api.facebook.com/1.0/}time"/>
 *         &lt;element name="sun_1_close" type="{http://api.facebook.com/1.0/}time"/>
 *         &lt;element name="mon_2_open" type="{http://api.facebook.com/1.0/}time"/>
 *         &lt;element name="mon_2_close" type="{http://api.facebook.com/1.0/}time"/>
 *         &lt;element name="tue_2_open" type="{http://api.facebook.com/1.0/}time"/>
 *         &lt;element name="tue_2_close" type="{http://api.facebook.com/1.0/}time"/>
 *         &lt;element name="wed_2_open" type="{http://api.facebook.com/1.0/}time"/>
 *         &lt;element name="wed_2_close" type="{http://api.facebook.com/1.0/}time"/>
 *         &lt;element name="thu_2_open" type="{http://api.facebook.com/1.0/}time"/>
 *         &lt;element name="thu_2_close" type="{http://api.facebook.com/1.0/}time"/>
 *         &lt;element name="fri_2_open" type="{http://api.facebook.com/1.0/}time"/>
 *         &lt;element name="fri_2_close" type="{http://api.facebook.com/1.0/}time"/>
 *         &lt;element name="sat_2_open" type="{http://api.facebook.com/1.0/}time"/>
 *         &lt;element name="sat_2_close" type="{http://api.facebook.com/1.0/}time"/>
 *         &lt;element name="sun_2_open" type="{http://api.facebook.com/1.0/}time"/>
 *         &lt;element name="sun_2_close" type="{http://api.facebook.com/1.0/}time"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "page_hours", propOrder = {
    "mon1Open",
    "mon1Close",
    "tue1Open",
    "tue1Close",
    "wed1Open",
    "thu1Open",
    "thu1Close",
    "fri1Open",
    "fri1Close",
    "sat1Open",
    "sat1Close",
    "sun1Open",
    "sun1Close",
    "mon2Open",
    "mon2Close",
    "tue2Open",
    "tue2Close",
    "wed2Open",
    "wed2Close",
    "thu2Open",
    "thu2Close",
    "fri2Open",
    "fri2Close",
    "sat2Open",
    "sat2Close",
    "sun2Open",
    "sun2Close"
})
public class PageHours {

    @XmlElement(name = "mon_1_open")
    protected int mon1Open;
    @XmlElement(name = "mon_1_close")
    protected int mon1Close;
    @XmlElement(name = "tue_1_open")
    protected int tue1Open;
    @XmlElement(name = "tue_1_close")
    protected int tue1Close;
    @XmlElement(name = "wed_1_open")
    protected int wed1Open;
    @XmlElement(name = "thu_1_open")
    protected int thu1Open;
    @XmlElement(name = "thu_1_close")
    protected int thu1Close;
    @XmlElement(name = "fri_1_open")
    protected int fri1Open;
    @XmlElement(name = "fri_1_close")
    protected int fri1Close;
    @XmlElement(name = "sat_1_open")
    protected int sat1Open;
    @XmlElement(name = "sat_1_close")
    protected int sat1Close;
    @XmlElement(name = "sun_1_open")
    protected int sun1Open;
    @XmlElement(name = "sun_1_close")
    protected int sun1Close;
    @XmlElement(name = "mon_2_open")
    protected int mon2Open;
    @XmlElement(name = "mon_2_close")
    protected int mon2Close;
    @XmlElement(name = "tue_2_open")
    protected int tue2Open;
    @XmlElement(name = "tue_2_close")
    protected int tue2Close;
    @XmlElement(name = "wed_2_open")
    protected int wed2Open;
    @XmlElement(name = "wed_2_close")
    protected int wed2Close;
    @XmlElement(name = "thu_2_open")
    protected int thu2Open;
    @XmlElement(name = "thu_2_close")
    protected int thu2Close;
    @XmlElement(name = "fri_2_open")
    protected int fri2Open;
    @XmlElement(name = "fri_2_close")
    protected int fri2Close;
    @XmlElement(name = "sat_2_open")
    protected int sat2Open;
    @XmlElement(name = "sat_2_close")
    protected int sat2Close;
    @XmlElement(name = "sun_2_open")
    protected int sun2Open;
    @XmlElement(name = "sun_2_close")
    protected int sun2Close;

    /**
     * Gets the value of the mon1Open property.
     * 
     */
    public int getMon1Open() {
        return mon1Open;
    }

    /**
     * Sets the value of the mon1Open property.
     * 
     */
    public void setMon1Open(int value) {
        this.mon1Open = value;
    }

    /**
     * Gets the value of the mon1Close property.
     * 
     */
    public int getMon1Close() {
        return mon1Close;
    }

    /**
     * Sets the value of the mon1Close property.
     * 
     */
    public void setMon1Close(int value) {
        this.mon1Close = value;
    }

    /**
     * Gets the value of the tue1Open property.
     * 
     */
    public int getTue1Open() {
        return tue1Open;
    }

    /**
     * Sets the value of the tue1Open property.
     * 
     */
    public void setTue1Open(int value) {
        this.tue1Open = value;
    }

    /**
     * Gets the value of the tue1Close property.
     * 
     */
    public int getTue1Close() {
        return tue1Close;
    }

    /**
     * Sets the value of the tue1Close property.
     * 
     */
    public void setTue1Close(int value) {
        this.tue1Close = value;
    }

    /**
     * Gets the value of the wed1Open property.
     * 
     */
    public int getWed1Open() {
        return wed1Open;
    }

    /**
     * Sets the value of the wed1Open property.
     * 
     */
    public void setWed1Open(int value) {
        this.wed1Open = value;
    }

    /**
     * Gets the value of the thu1Open property.
     * 
     */
    public int getThu1Open() {
        return thu1Open;
    }

    /**
     * Sets the value of the thu1Open property.
     * 
     */
    public void setThu1Open(int value) {
        this.thu1Open = value;
    }

    /**
     * Gets the value of the thu1Close property.
     * 
     */
    public int getThu1Close() {
        return thu1Close;
    }

    /**
     * Sets the value of the thu1Close property.
     * 
     */
    public void setThu1Close(int value) {
        this.thu1Close = value;
    }

    /**
     * Gets the value of the fri1Open property.
     * 
     */
    public int getFri1Open() {
        return fri1Open;
    }

    /**
     * Sets the value of the fri1Open property.
     * 
     */
    public void setFri1Open(int value) {
        this.fri1Open = value;
    }

    /**
     * Gets the value of the fri1Close property.
     * 
     */
    public int getFri1Close() {
        return fri1Close;
    }

    /**
     * Sets the value of the fri1Close property.
     * 
     */
    public void setFri1Close(int value) {
        this.fri1Close = value;
    }

    /**
     * Gets the value of the sat1Open property.
     * 
     */
    public int getSat1Open() {
        return sat1Open;
    }

    /**
     * Sets the value of the sat1Open property.
     * 
     */
    public void setSat1Open(int value) {
        this.sat1Open = value;
    }

    /**
     * Gets the value of the sat1Close property.
     * 
     */
    public int getSat1Close() {
        return sat1Close;
    }

    /**
     * Sets the value of the sat1Close property.
     * 
     */
    public void setSat1Close(int value) {
        this.sat1Close = value;
    }

    /**
     * Gets the value of the sun1Open property.
     * 
     */
    public int getSun1Open() {
        return sun1Open;
    }

    /**
     * Sets the value of the sun1Open property.
     * 
     */
    public void setSun1Open(int value) {
        this.sun1Open = value;
    }

    /**
     * Gets the value of the sun1Close property.
     * 
     */
    public int getSun1Close() {
        return sun1Close;
    }

    /**
     * Sets the value of the sun1Close property.
     * 
     */
    public void setSun1Close(int value) {
        this.sun1Close = value;
    }

    /**
     * Gets the value of the mon2Open property.
     * 
     */
    public int getMon2Open() {
        return mon2Open;
    }

    /**
     * Sets the value of the mon2Open property.
     * 
     */
    public void setMon2Open(int value) {
        this.mon2Open = value;
    }

    /**
     * Gets the value of the mon2Close property.
     * 
     */
    public int getMon2Close() {
        return mon2Close;
    }

    /**
     * Sets the value of the mon2Close property.
     * 
     */
    public void setMon2Close(int value) {
        this.mon2Close = value;
    }

    /**
     * Gets the value of the tue2Open property.
     * 
     */
    public int getTue2Open() {
        return tue2Open;
    }

    /**
     * Sets the value of the tue2Open property.
     * 
     */
    public void setTue2Open(int value) {
        this.tue2Open = value;
    }

    /**
     * Gets the value of the tue2Close property.
     * 
     */
    public int getTue2Close() {
        return tue2Close;
    }

    /**
     * Sets the value of the tue2Close property.
     * 
     */
    public void setTue2Close(int value) {
        this.tue2Close = value;
    }

    /**
     * Gets the value of the wed2Open property.
     * 
     */
    public int getWed2Open() {
        return wed2Open;
    }

    /**
     * Sets the value of the wed2Open property.
     * 
     */
    public void setWed2Open(int value) {
        this.wed2Open = value;
    }

    /**
     * Gets the value of the wed2Close property.
     * 
     */
    public int getWed2Close() {
        return wed2Close;
    }

    /**
     * Sets the value of the wed2Close property.
     * 
     */
    public void setWed2Close(int value) {
        this.wed2Close = value;
    }

    /**
     * Gets the value of the thu2Open property.
     * 
     */
    public int getThu2Open() {
        return thu2Open;
    }

    /**
     * Sets the value of the thu2Open property.
     * 
     */
    public void setThu2Open(int value) {
        this.thu2Open = value;
    }

    /**
     * Gets the value of the thu2Close property.
     * 
     */
    public int getThu2Close() {
        return thu2Close;
    }

    /**
     * Sets the value of the thu2Close property.
     * 
     */
    public void setThu2Close(int value) {
        this.thu2Close = value;
    }

    /**
     * Gets the value of the fri2Open property.
     * 
     */
    public int getFri2Open() {
        return fri2Open;
    }

    /**
     * Sets the value of the fri2Open property.
     * 
     */
    public void setFri2Open(int value) {
        this.fri2Open = value;
    }

    /**
     * Gets the value of the fri2Close property.
     * 
     */
    public int getFri2Close() {
        return fri2Close;
    }

    /**
     * Sets the value of the fri2Close property.
     * 
     */
    public void setFri2Close(int value) {
        this.fri2Close = value;
    }

    /**
     * Gets the value of the sat2Open property.
     * 
     */
    public int getSat2Open() {
        return sat2Open;
    }

    /**
     * Sets the value of the sat2Open property.
     * 
     */
    public void setSat2Open(int value) {
        this.sat2Open = value;
    }

    /**
     * Gets the value of the sat2Close property.
     * 
     */
    public int getSat2Close() {
        return sat2Close;
    }

    /**
     * Sets the value of the sat2Close property.
     * 
     */
    public void setSat2Close(int value) {
        this.sat2Close = value;
    }

    /**
     * Gets the value of the sun2Open property.
     * 
     */
    public int getSun2Open() {
        return sun2Open;
    }

    /**
     * Sets the value of the sun2Open property.
     * 
     */
    public void setSun2Open(int value) {
        this.sun2Open = value;
    }

    /**
     * Gets the value of the sun2Close property.
     * 
     */
    public int getSun2Close() {
        return sun2Close;
    }

    /**
     * Sets the value of the sun2Close property.
     * 
     */
    public void setSun2Close(int value) {
        this.sun2Close = value;
    }

}
