//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.08 at 04:00:59 PM PDT 
//


package com.facebook.api.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for page complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="page">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="page_id" type="{http://api.facebook.com/1.0/}page_id" minOccurs="0"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pic_small" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pic_big" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pic_square" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pic" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pic_large" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="page_url" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="status" type="{http://api.facebook.com/1.0/}user_status" minOccurs="0"/>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="website" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="has_added_app" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="founded" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="company_overview" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="mission" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="products" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="location" type="{http://api.facebook.com/1.0/}location" minOccurs="0"/>
 *         &lt;element name="parking" type="{http://api.facebook.com/1.0/}page_parking" minOccurs="0"/>
 *         &lt;element name="public_transit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="hours" type="{http://api.facebook.com/1.0/}page_hours" minOccurs="0"/>
 *         &lt;element name="attire" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="payment_options" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="culinary_team" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="general_manager" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="price_range" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="restaurant_services" type="{http://api.facebook.com/1.0/}page_restaurant_services" minOccurs="0"/>
 *         &lt;element name="restaurant_specialties" type="{http://api.facebook.com/1.0/}page_restaurant_specialties" minOccurs="0"/>
 *         &lt;element name="release_date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="genre" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="starring" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="screenplay_by" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="directed_by" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="produced_by" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="studio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="awards" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="plot_outline" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="network" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="season" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="schedule" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="written_by" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="band_members" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="hometown" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="current_location" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="record_label" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="booking_agent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="artists_we_like" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="influences" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="band_interests" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="bio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="affiliation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="birthday" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="personal_info" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="personal_interests" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="members" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="built" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="features" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="mpg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="general_info" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "page", propOrder = {

})
public class Page {

    @XmlElement(name = "page_id")
    protected Long pageId;
    protected String name;
    @XmlElementRef(name = "pic_small", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> picSmall;
    @XmlElementRef(name = "pic_big", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> picBig;
    @XmlElementRef(name = "pic_square", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> picSquare;
    @XmlElementRef(name = "pic", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> pic;
    @XmlElementRef(name = "pic_large", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> picLarge;
    @XmlElement(name = "page_url")
    protected String pageUrl;
    @XmlElementRef(name = "status", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<UserStatus> status;
    protected String type;
    @XmlElementRef(name = "website", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> website;
    @XmlElementRef(name = "has_added_app", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<Boolean> hasAddedApp;
    @XmlElementRef(name = "founded", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> founded;
    @XmlElementRef(name = "company_overview", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> companyOverview;
    @XmlElementRef(name = "mission", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> mission;
    @XmlElementRef(name = "products", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> products;
    @XmlElementRef(name = "location", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<Location> location;
    @XmlElementRef(name = "parking", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<PageParking> parking;
    @XmlElementRef(name = "public_transit", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> publicTransit;
    @XmlElementRef(name = "hours", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<PageHours> hours;
    @XmlElementRef(name = "attire", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> attire;
    @XmlElementRef(name = "payment_options", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> paymentOptions;
    @XmlElementRef(name = "culinary_team", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> culinaryTeam;
    @XmlElementRef(name = "general_manager", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> generalManager;
    @XmlElementRef(name = "price_range", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> priceRange;
    @XmlElementRef(name = "restaurant_services", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<PageRestaurantServices> restaurantServices;
    @XmlElementRef(name = "restaurant_specialties", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<PageRestaurantSpecialties> restaurantSpecialties;
    @XmlElementRef(name = "release_date", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> releaseDate;
    @XmlElementRef(name = "genre", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> genre;
    @XmlElementRef(name = "starring", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> starring;
    @XmlElementRef(name = "screenplay_by", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> screenplayBy;
    @XmlElementRef(name = "directed_by", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> directedBy;
    @XmlElementRef(name = "produced_by", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> producedBy;
    @XmlElementRef(name = "studio", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> studio;
    @XmlElementRef(name = "awards", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> awards;
    @XmlElementRef(name = "plot_outline", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> plotOutline;
    @XmlElementRef(name = "network", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> network;
    @XmlElementRef(name = "season", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> season;
    @XmlElementRef(name = "schedule", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> schedule;
    @XmlElementRef(name = "written_by", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> writtenBy;
    @XmlElementRef(name = "band_members", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> bandMembers;
    @XmlElementRef(name = "hometown", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> hometown;
    @XmlElementRef(name = "current_location", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> currentLocation;
    @XmlElementRef(name = "record_label", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> recordLabel;
    @XmlElementRef(name = "booking_agent", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> bookingAgent;
    @XmlElementRef(name = "artists_we_like", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> artistsWeLike;
    @XmlElementRef(name = "influences", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> influences;
    @XmlElementRef(name = "band_interests", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> bandInterests;
    @XmlElementRef(name = "bio", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> bio;
    @XmlElementRef(name = "affiliation", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> affiliation;
    @XmlElementRef(name = "birthday", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> birthday;
    @XmlElementRef(name = "personal_info", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> personalInfo;
    @XmlElementRef(name = "personal_interests", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> personalInterests;
    @XmlElementRef(name = "members", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> members;
    @XmlElementRef(name = "built", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> built;
    @XmlElementRef(name = "features", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> features;
    @XmlElementRef(name = "mpg", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> mpg;
    @XmlElementRef(name = "general_info", namespace = "http://api.facebook.com/1.0/", type = JAXBElement.class)
    protected JAXBElement<String> generalInfo;

    /**
     * Gets the value of the pageId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getPageId() {
        return pageId;
    }

    /**
     * Sets the value of the pageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setPageId(Long value) {
        this.pageId = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the picSmall property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPicSmall() {
        return picSmall;
    }

    /**
     * Sets the value of the picSmall property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPicSmall(JAXBElement<String> value) {
        this.picSmall = value;
    }

    /**
     * Gets the value of the picBig property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPicBig() {
        return picBig;
    }

    /**
     * Sets the value of the picBig property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPicBig(JAXBElement<String> value) {
        this.picBig = value;
    }

    /**
     * Gets the value of the picSquare property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPicSquare() {
        return picSquare;
    }

    /**
     * Sets the value of the picSquare property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPicSquare(JAXBElement<String> value) {
        this.picSquare = value;
    }

    /**
     * Gets the value of the pic property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPic() {
        return pic;
    }

    /**
     * Sets the value of the pic property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPic(JAXBElement<String> value) {
        this.pic = value;
    }

    /**
     * Gets the value of the picLarge property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPicLarge() {
        return picLarge;
    }

    /**
     * Sets the value of the picLarge property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPicLarge(JAXBElement<String> value) {
        this.picLarge = value;
    }

    /**
     * Gets the value of the pageUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPageUrl() {
        return pageUrl;
    }

    /**
     * Sets the value of the pageUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPageUrl(String value) {
        this.pageUrl = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link UserStatus }{@code >}
     *     
     */
    public JAXBElement<UserStatus> getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link UserStatus }{@code >}
     *     
     */
    public void setStatus(JAXBElement<UserStatus> value) {
        this.status = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the website property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getWebsite() {
        return website;
    }

    /**
     * Sets the value of the website property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setWebsite(JAXBElement<String> value) {
        this.website = value;
    }

    /**
     * Gets the value of the hasAddedApp property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     *     
     */
    public JAXBElement<Boolean> getHasAddedApp() {
        return hasAddedApp;
    }

    /**
     * Sets the value of the hasAddedApp property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     *     
     */
    public void setHasAddedApp(JAXBElement<Boolean> value) {
        this.hasAddedApp = value;
    }

    /**
     * Gets the value of the founded property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getFounded() {
        return founded;
    }

    /**
     * Sets the value of the founded property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setFounded(JAXBElement<String> value) {
        this.founded = value;
    }

    /**
     * Gets the value of the companyOverview property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCompanyOverview() {
        return companyOverview;
    }

    /**
     * Sets the value of the companyOverview property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCompanyOverview(JAXBElement<String> value) {
        this.companyOverview = value;
    }

    /**
     * Gets the value of the mission property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getMission() {
        return mission;
    }

    /**
     * Sets the value of the mission property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setMission(JAXBElement<String> value) {
        this.mission = value;
    }

    /**
     * Gets the value of the products property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getProducts() {
        return products;
    }

    /**
     * Sets the value of the products property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setProducts(JAXBElement<String> value) {
        this.products = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Location }{@code >}
     *     
     */
    public JAXBElement<Location> getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Location }{@code >}
     *     
     */
    public void setLocation(JAXBElement<Location> value) {
        this.location = value;
    }

    /**
     * Gets the value of the parking property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PageParking }{@code >}
     *     
     */
    public JAXBElement<PageParking> getParking() {
        return parking;
    }

    /**
     * Sets the value of the parking property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PageParking }{@code >}
     *     
     */
    public void setParking(JAXBElement<PageParking> value) {
        this.parking = value;
    }

    /**
     * Gets the value of the publicTransit property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPublicTransit() {
        return publicTransit;
    }

    /**
     * Sets the value of the publicTransit property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPublicTransit(JAXBElement<String> value) {
        this.publicTransit = value;
    }

    /**
     * Gets the value of the hours property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PageHours }{@code >}
     *     
     */
    public JAXBElement<PageHours> getHours() {
        return hours;
    }

    /**
     * Sets the value of the hours property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PageHours }{@code >}
     *     
     */
    public void setHours(JAXBElement<PageHours> value) {
        this.hours = value;
    }

    /**
     * Gets the value of the attire property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAttire() {
        return attire;
    }

    /**
     * Sets the value of the attire property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAttire(JAXBElement<String> value) {
        this.attire = value;
    }

    /**
     * Gets the value of the paymentOptions property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPaymentOptions() {
        return paymentOptions;
    }

    /**
     * Sets the value of the paymentOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPaymentOptions(JAXBElement<String> value) {
        this.paymentOptions = value;
    }

    /**
     * Gets the value of the culinaryTeam property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCulinaryTeam() {
        return culinaryTeam;
    }

    /**
     * Sets the value of the culinaryTeam property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCulinaryTeam(JAXBElement<String> value) {
        this.culinaryTeam = value;
    }

    /**
     * Gets the value of the generalManager property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getGeneralManager() {
        return generalManager;
    }

    /**
     * Sets the value of the generalManager property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setGeneralManager(JAXBElement<String> value) {
        this.generalManager = value;
    }

    /**
     * Gets the value of the priceRange property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPriceRange() {
        return priceRange;
    }

    /**
     * Sets the value of the priceRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPriceRange(JAXBElement<String> value) {
        this.priceRange = value;
    }

    /**
     * Gets the value of the restaurantServices property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PageRestaurantServices }{@code >}
     *     
     */
    public JAXBElement<PageRestaurantServices> getRestaurantServices() {
        return restaurantServices;
    }

    /**
     * Sets the value of the restaurantServices property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PageRestaurantServices }{@code >}
     *     
     */
    public void setRestaurantServices(JAXBElement<PageRestaurantServices> value) {
        this.restaurantServices = value;
    }

    /**
     * Gets the value of the restaurantSpecialties property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PageRestaurantSpecialties }{@code >}
     *     
     */
    public JAXBElement<PageRestaurantSpecialties> getRestaurantSpecialties() {
        return restaurantSpecialties;
    }

    /**
     * Sets the value of the restaurantSpecialties property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PageRestaurantSpecialties }{@code >}
     *     
     */
    public void setRestaurantSpecialties(JAXBElement<PageRestaurantSpecialties> value) {
        this.restaurantSpecialties = value;
    }

    /**
     * Gets the value of the releaseDate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getReleaseDate() {
        return releaseDate;
    }

    /**
     * Sets the value of the releaseDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setReleaseDate(JAXBElement<String> value) {
        this.releaseDate = value;
    }

    /**
     * Gets the value of the genre property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getGenre() {
        return genre;
    }

    /**
     * Sets the value of the genre property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setGenre(JAXBElement<String> value) {
        this.genre = value;
    }

    /**
     * Gets the value of the starring property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getStarring() {
        return starring;
    }

    /**
     * Sets the value of the starring property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setStarring(JAXBElement<String> value) {
        this.starring = value;
    }

    /**
     * Gets the value of the screenplayBy property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getScreenplayBy() {
        return screenplayBy;
    }

    /**
     * Sets the value of the screenplayBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setScreenplayBy(JAXBElement<String> value) {
        this.screenplayBy = value;
    }

    /**
     * Gets the value of the directedBy property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDirectedBy() {
        return directedBy;
    }

    /**
     * Sets the value of the directedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDirectedBy(JAXBElement<String> value) {
        this.directedBy = value;
    }

    /**
     * Gets the value of the producedBy property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getProducedBy() {
        return producedBy;
    }

    /**
     * Sets the value of the producedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setProducedBy(JAXBElement<String> value) {
        this.producedBy = value;
    }

    /**
     * Gets the value of the studio property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getStudio() {
        return studio;
    }

    /**
     * Sets the value of the studio property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setStudio(JAXBElement<String> value) {
        this.studio = value;
    }

    /**
     * Gets the value of the awards property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAwards() {
        return awards;
    }

    /**
     * Sets the value of the awards property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAwards(JAXBElement<String> value) {
        this.awards = value;
    }

    /**
     * Gets the value of the plotOutline property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPlotOutline() {
        return plotOutline;
    }

    /**
     * Sets the value of the plotOutline property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPlotOutline(JAXBElement<String> value) {
        this.plotOutline = value;
    }

    /**
     * Gets the value of the network property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getNetwork() {
        return network;
    }

    /**
     * Sets the value of the network property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setNetwork(JAXBElement<String> value) {
        this.network = value;
    }

    /**
     * Gets the value of the season property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSeason() {
        return season;
    }

    /**
     * Sets the value of the season property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSeason(JAXBElement<String> value) {
        this.season = value;
    }

    /**
     * Gets the value of the schedule property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSchedule() {
        return schedule;
    }

    /**
     * Sets the value of the schedule property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSchedule(JAXBElement<String> value) {
        this.schedule = value;
    }

    /**
     * Gets the value of the writtenBy property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getWrittenBy() {
        return writtenBy;
    }

    /**
     * Sets the value of the writtenBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setWrittenBy(JAXBElement<String> value) {
        this.writtenBy = value;
    }

    /**
     * Gets the value of the bandMembers property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getBandMembers() {
        return bandMembers;
    }

    /**
     * Sets the value of the bandMembers property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setBandMembers(JAXBElement<String> value) {
        this.bandMembers = value;
    }

    /**
     * Gets the value of the hometown property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getHometown() {
        return hometown;
    }

    /**
     * Sets the value of the hometown property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setHometown(JAXBElement<String> value) {
        this.hometown = value;
    }

    /**
     * Gets the value of the currentLocation property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCurrentLocation() {
        return currentLocation;
    }

    /**
     * Sets the value of the currentLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCurrentLocation(JAXBElement<String> value) {
        this.currentLocation = value;
    }

    /**
     * Gets the value of the recordLabel property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRecordLabel() {
        return recordLabel;
    }

    /**
     * Sets the value of the recordLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRecordLabel(JAXBElement<String> value) {
        this.recordLabel = value;
    }

    /**
     * Gets the value of the bookingAgent property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getBookingAgent() {
        return bookingAgent;
    }

    /**
     * Sets the value of the bookingAgent property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setBookingAgent(JAXBElement<String> value) {
        this.bookingAgent = value;
    }

    /**
     * Gets the value of the artistsWeLike property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getArtistsWeLike() {
        return artistsWeLike;
    }

    /**
     * Sets the value of the artistsWeLike property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setArtistsWeLike(JAXBElement<String> value) {
        this.artistsWeLike = value;
    }

    /**
     * Gets the value of the influences property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getInfluences() {
        return influences;
    }

    /**
     * Sets the value of the influences property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setInfluences(JAXBElement<String> value) {
        this.influences = value;
    }

    /**
     * Gets the value of the bandInterests property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getBandInterests() {
        return bandInterests;
    }

    /**
     * Sets the value of the bandInterests property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setBandInterests(JAXBElement<String> value) {
        this.bandInterests = value;
    }

    /**
     * Gets the value of the bio property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getBio() {
        return bio;
    }

    /**
     * Sets the value of the bio property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setBio(JAXBElement<String> value) {
        this.bio = value;
    }

    /**
     * Gets the value of the affiliation property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAffiliation() {
        return affiliation;
    }

    /**
     * Sets the value of the affiliation property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAffiliation(JAXBElement<String> value) {
        this.affiliation = value;
    }

    /**
     * Gets the value of the birthday property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getBirthday() {
        return birthday;
    }

    /**
     * Sets the value of the birthday property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setBirthday(JAXBElement<String> value) {
        this.birthday = value;
    }

    /**
     * Gets the value of the personalInfo property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPersonalInfo() {
        return personalInfo;
    }

    /**
     * Sets the value of the personalInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPersonalInfo(JAXBElement<String> value) {
        this.personalInfo = value;
    }

    /**
     * Gets the value of the personalInterests property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPersonalInterests() {
        return personalInterests;
    }

    /**
     * Sets the value of the personalInterests property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPersonalInterests(JAXBElement<String> value) {
        this.personalInterests = value;
    }

    /**
     * Gets the value of the members property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getMembers() {
        return members;
    }

    /**
     * Sets the value of the members property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setMembers(JAXBElement<String> value) {
        this.members = value;
    }

    /**
     * Gets the value of the built property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getBuilt() {
        return built;
    }

    /**
     * Sets the value of the built property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setBuilt(JAXBElement<String> value) {
        this.built = value;
    }

    /**
     * Gets the value of the features property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getFeatures() {
        return features;
    }

    /**
     * Sets the value of the features property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setFeatures(JAXBElement<String> value) {
        this.features = value;
    }

    /**
     * Gets the value of the mpg property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getMpg() {
        return mpg;
    }

    /**
     * Sets the value of the mpg property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setMpg(JAXBElement<String> value) {
        this.mpg = value;
    }

    /**
     * Gets the value of the generalInfo property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getGeneralInfo() {
        return generalInfo;
    }

    /**
     * Sets the value of the generalInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setGeneralInfo(JAXBElement<String> value) {
        this.generalInfo = value;
    }

}
